project:
  type: website
  output-dir: docs

website:
  title: "PSYC 6019"
  description: "Webpage for Statistical Analysis I taught in Fall 2026 at Georgia Tech."
  site-url: "https://jhelmer3.github.io/PSYC6019-2026/"
  navbar:
    tools: 
      - icon: github
        href:  https://github.com/jhelmer3/PSYC6019-2026
    left:
      - href: index.qmd
      - href: syllabus.qmd
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

format:
  html:
    theme: gt-theme.scss
    toc: true

