---
title: "Extra Credit"
subtitle: Fall 2026
date: last-modified
author: Mark Himmelstein and Jess Helmer
format: html
---

# posit::conf(2026)

[Posit](https://posit.co/), the organization that makes RStudio, has a [conference](https://posit.co/conference/) every year about data science called posit::conf(), and they offer a free registration tier for people attending virtually. 

Attending livestreamed sessions from this conference (September 14th–16th) and writing a brief report about what you learned will be an opportunity for extra credit added to your first homework grade. This will be distributed as 0.5 points for each session and report, with a maximum of 1 point for attending two sessions. The report must be completed in Quarto. The goal of this extra credit assignment is to provide more exposure to the latest and greatest developments in R and data science and give you a low-stakes opportunity to practice your R and Quarto chops.

To attend the conference, you will need to [register at this link](https://conf.posit.co/2026/registration/).  

1. Follow the steps through "Attendance Type"

2. Select that you will be attending the conference **virtually**  

3. When asked which ticket type, select the **Needs-Based** (for free attendance) [I (Jess) have confirmed with Posit that we are approved to use the needs-based registration option for this extra credit assignment!]{.aside}

4. Add one conference pass

5. There is no free tier for the day-before workshop. On the "Add-Ons" page, you can skip the workshop by not clicking "Select" and instead just clicking "Continue"

6. Finish registering by clicking "Continue" and "Register Now"

After registering, you will get an email with dates and info about the conference. Instructions for how to access the sessions, which will be livestreamed September 14th--16th and will be about an hour long each, will be sent later. Live attendance is required for this extra credit assignment. If there is a particular session you want to attend but you have a conflict with the time, please let Jess and Mark know **in advance**. We cannot guarantee credit for watching the on-demand versions without prior discussion.

To complete the assignment, attend a session live, and take a screenshot of the live session with the current date / time on the screen. Make sure to save this screenshot: it is required for credit! Afterwards, write a brief (150±50 words) summary of the session. Make sure you include the title of the session. If the session is a symposium (multiple speakers), make sure to include a sentence or two about each of the speakers. Multiple speakers within a symposium session do not count as multiple sessions. Include your screenshot in your writeup. Instructions for including images in Quart are available [here](https://quarto.org/docs/authoring/figures.html). If you attend two sessions, please include both summaries and screenshots in the same document. Please upload both your .html and .qmd files. 

Please know that these sessions are likely to be advanced! We do *not* expect you to fully understand or be able to apply the content. The intention of this assignment is to get to know what's "out there" in the R and data science worlds. The [full schedule is here](https://irp.cdn-website.com/d4d6e48c/files/uploaded/PST-Conf26-AgendaAtAGlance-preConf-v5.pdf). 

Feel free to attend whichever sessions you choose, but we will include some recommendations for sessions to attend below closer to the conference.

<!-- | Date | Time | Topic | -->
<!-- |------|------|-------| -->
<!-- | 9/17| 9--10am | 10 Years of Data Science Tools... and What Happens Next | -->
<!-- | 9/17 | 1--2:20pm | Lightning Talks | -->
<!-- | 9/17 | 2:40-4pm | Quarto (this is how I (Jess) make my slides!) | -->
<!-- | 9/17 | 4:15--5:15pm | Making the most of artificial and human intelligence for data science | -->
<!-- | 9/18 | 10:20--11:40am | Data for Real-World Impact | -->
<!-- | 9/18 | 1:00-2:20pm | Beautiful, Effective, and Accessible Data Visualization | -->
<!-- | 9/18 | 4:15--5:15pm | Trustworthy Data Visualization | -->

<!-- I've done my best to make sure these are accurate, but make sure to confirm these session day and times with the [official posit::conf(2025) schedule](https://reg.rainfocus.com/flow/posit/positconf25/attendee-portal/page/sessioncatalog?tab.day=20250916).  -->

<!-- Submit this assignment by September 25th (one week after the last day of the conference)! We will not be able to credit late assignments. Have fun at posit::conf(2025)! -->