---
title: "Syllabus"
subtitle: "PSYC 6019: Statistical Analysis I"
date: last-modified
author: Mark Himmelstein and Jess Helmer
format: html
---

# Statistical Analysis I

|              |   Lecture    |   Lab     |
|---------|-----------|-----------|
| Instructor   | Mark Himmelstein <br> [mhimmelstein3@gatech.edu](mailto:mhimmelstein3@gatech.edu) | Jessica Helmer <br> [jhelmer3@gatech.edu](mailto:jhelmer3@gatech.edu)  |
| Lecture Time | Tuesdays and Thursdays <br> 3:00pm–5:25pm | Fridays <br> 2:00pm–4:45pm |
| Location     | JS Coon, Room 250 | JS Coon, Room 248 |
| Office Hours | JS Coon, Room 235 <br> Tuesdays 1pm–2pm | JS Coon, Room 241 or [Zoom](https://gatech.zoom.us/j/99304234613?pwd=RaHoZaucbajqE1VZzClFi7XF8bpn6l.1) <br> Fridays 1pm–2pm

This syllabus provides a general overview and plan for this course. Deviations may be necessary. I will alert you as soon as possible should any occur.


# Course Description

This course provides the necessary tools for baseline statistical literacy for graduate students in psychology and broader social science. Topics will include probability, descriptive statistics and data visualization, inferential statistics and hypothesis testing, experimental design and analysis, and an introduction to Bayesian data analysis.

## Course Objectives

1. Achieve a level of statistical literacy appropriate for graduate level research productivity in psychology and social science

2. Learn how to convert experimental and observational quantitative data into actionable and valid scientific insight

3. Learn how to use R to conduct statistical analyses and generate scientific reports.

## Readings

### Lecture

There are no required textbooks. Suggested readings will be from the following free online resources:

|                  |
|------------------|
| Poldrack, R. A. (2019). Statistical Thinking for the 21st Century. [statsthinking21.github.io/statsthinking21-core-site](https://statsthinking21.github.io/statsthinking21-core-site/) | 
| Lane, D.M. Online Statistics Education: A Multimedia Course of Study. [onlinestatbook.com](http://onlinestatbook.com/) |
| Barr, Dale J. (2021). Learning statistical models through simulation in R: An interactive textbook. Version 1.0.0. [psyteachr.github.io/stat-models-v1](https://psyteachr.github.io/stat-models-v1) |
| Navarro, D. Learning statistics with R. [learningstatisticswithr.com](https://learningstatisticswithr.com/) |
| Crump, M. J. C., Navarro, D. J., & Suzuki, J. (2019). Answering Questions with Data: Introductory Statistics for Psychology Students. [crumplab.com/psyc3400](https://www.crumplab.com/psyc3400/) |
| Nguyen, M. (2025). Advanced modeling and data challenges (Vol. 3). Springer Cham. [link.springer.com/book/9783032017185](https://link.springer.com/book/9783032017185) (Access via Georgia Tech Library) |

<br>

Suggested readings are listed on the course schedule. These are **extremely** helpful but will not be required for assignments or exams.  

### Lab

Suggested readings are listed on the course schedule. These are extremely helpful but will not be required for assignments or exams. 

The lab for this course will use the R software through the RStudio interface. We will also learn to use the Quarto language within RStudio to create reproducible reports that weave together R code, R output and plots, and text. R and RStudio are free and openly available for all users.

|                    |
|--------------------| 
| The Comprehensive R Archive Network: [cran.r-project.org](https://cran.r-project.org/) |
| RStudio: [rstudio.com](https://www.rstudio.com/) |
| Quarto: [quarto.org/docs/guide](https://quarto.org/docs/guide/) |

<br>

Cheat sheets for R and R Markdown will be posted on Canvas. In addition, you may find the following resources helpful:

|                    |
|--------------------|
| More RStudio cheat sheets: [rstudio.github.io/cheatsheets/contributed-cheatsheets.html](https://rstudio.github.io/cheatsheets/contributed-cheatsheets.html) |
| More about the `{tidyverse}`: [cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html) |
| Tidy Tuesday: [twitter.com/search?q=tidytuesday ](https://twitter.com/search?q=tidytuesday) |
| R bloggers: [r-bloggers.com](https://www.r-bloggers.com) |
| Online courses: <br> ○ [rstudio.com/resources/training](https://www.rstudio.com/resources/training/) <br> ○ [datacamp.com/courses/free-introduction-to-r](https://www.datacamp.com/courses/free-introduction-to-r) <br> ○ [udemy.com/r-basics](https://www.udemy.com/r-basics/) <br> ○  [edx.org/course/data-science-r-basics-2](https://www.edx.org/course/data-science-r-basics-2) |

### Additional Readings

Additional readings pertaining to specific topics will be posted on Canvas.


## Course Structure

Lectures in this course will be held in person. Each lecture will be recorded and posted online within 24 hours (if I forget, please remind me!)


## Attendance Policy

Students should plan to attend all lecture and lab sessions in person. If you feel unwell, please let the instructor know and stay home! 

Every lecture session will be connected to a recorded Zoom session. Students who are not able to attend in person but feel well enough to learn should plan to join the Zoom session. Students who can neither attend in person nor join the Zoom session should watch and take notes from the recording and be in contact with the instructor. 

In the event of an absence, you are responsible for all missed materials, assignments, and any additional announcements or schedule changes given in class.



# Grading


## Grade Components

### 1. Exams (36%) 

There will be three non-cumulative exams, two midterms and one final, worth 12% of your grade each. Exams will be held in person during designated class time. They will have two components: a theoretical component and applied component. The theoretical component will refer primarily to material covered during lecture. The applied component will require you to use R to conduct a statistical analysis and produce a report. You are permitted to use any materials at your disposal to complete exams ***except for generative artificial intelligence***. This includes textbooks, lecture notes, prior assignments, and online resources. Usage of AI will result in an automatic failing grade.  

### 2. Homework Assignments (30%) 

There will be **six (6) homework assignments** throughout the course of the semester. Homework assignments can be found and submitted on Canvas. They will include content covered in both lecture and lab. They will be due on Thursdays at 11:59pm ET during weeks indicated on the course schedule. You are encouraged to discuss assignments with the course instructors and your classmates, including on Ed Discussion (see below). However, you are expected to submit your own work on homework assignments. Submitting other’s work as your own is considered plagiarism, and if necessary, will be dealt with through Georgia Tech’s disciplinary process. 

### 3. Lab Activities (14%) 

Students are expected to attend and participate in all scheduled labs. There are 14 labs which will be hosted by the Lab Instructor and will consist of a short R presentation / demonstration followed by a brief activity. Students are expected to work on the activity during the scheduled lab time. Lab activities will be due at 11:59pm on the day they are assigned and graded as complete or incomplete. As long as a complete attempt is made, credit will be given. Late assignments will not be accepted. 

### 4. Lab Project (10%)

The goal of the extra credit lab option is to get you started on an independent research project that will aid your educational or career development beyond mastery of the core course content. You must provide a dataset of your own (instructors can make suggestions for publicly available data sources if you would like) and produce a Quarto report in which includes a brief introduction, methods, results, and discussion section. The results section must report descriptive statistics, at least two (2) inferential methods learned in class, and at least two (2) data visualization methods learned in class. One inferential method must be frequentist and the other Bayesian (you may treat one as a robustness check on the other). The primary goal is to provide you an opportunity to work independently on statistical analysis while you have the resources of course instructors available to you. The report must be in proper APA format. 

### 5. Ed Discussion (10%) 

Though in-class participation will be encouraged, this course will also have an asynchronous discussion component via Ed Discussion. The system is highly catered to getting you help fast and efficiently from instructors, TAs, and classmates. To receive full credit for the **Ed Discussion** portion of your grade you must make at least **10 qualifying posts** throughout the semester. Qualifying posts can be questions involving statistical concepts, questions about how write code to solve a problem, thoughts about your approach to Lab Assignments, or anything else relevant to course material. You are encouraged to answer each other’s questions where possible, but course instructors will also be on hand to reply, and particularly notable questions may be brought up during lectures or labs for further live discussion. You are also encouraged to use Ed Discussion for purely logistical questions, but these will not count towards your grade. 

Most of your Ed Discussion posts should be made to the full class. The exception is if you have a question about a particular assignment, quiz, or anything else that could spoil answers for classmates. In these cases, you should post to instructors only. Please post these messages rather than email or direct message them, as we may determine they are OK to make public (with your permission) if we think it would be helpful to others. 


### 6. Extra Credit R Conference (Optional) 

[Posit](https://posit.co/), the organization that makes RStudio, has a [conference](https://posit.co/conference/) every year about data science called posit::conf(), and they offer a free registration tier for people attending virtually. Attending livestreamed sessions from this conference (September 14th--16th) and writing a brief report about what you learned will be an opportunity for extra credit added to your first homework grade. This will be distributed as 0.5 points for each session and report, with a maximum of 1 point for attending two sessions. The report must be completed in Quarto. The goal of this extra credit assignment is to provide more exposure to the latest and greatest developments in R and data science and give you a low-stakes opportunity to practice your R and Quarto chops. Details on how to register for the conference, recommended sessions, and guidance for the report will be shared closer to the conference. 


## Final Grade Criteria

A: 90% or higher

B: 80-89%

C: 70-79%

D: 60-69%

F: Lower than 60%



# University and Classroom Policies


## Academic Integrity

Georgia tech aims to cultivate a community based on trust, academic integrity, and Honor. Students are expected to act according to the highest ethical standards. For information on Georgia Tech’s academic honor code, please visit [catalog.gatech.edu/policies/honor-code](http://www.catalog.gatech.edu/policies/honor-code/) or [catalog.gatech.edu/rules/18](http://www.catalog.gatech.edu/rules/18/). Any student suspected of cheating or plagiarizing on a quiz, exam, or assignment will be reported to the Office of Student Integrity, who will investigate the incident and identify the appropriate penalty for violations.


## Use of ChatGPT or Other AI Resources

ChatGPT is a useful tool, but it is far from perfect. There are no strict restrictions on using such tools as a **learning resource**. **However, your final submitted work must be your own original work**. If you use resources such as ChatGPT to assist in your learning, you are solely responsible for verifying the accuracy of information provided, and **any submissions of graded material suspected of being generated by ChatGPT or other AI tool constitutes plagiarism** and will be handled in accordance with class and Georgia Tech academic integrity policies. 


## Office of Disability Services

If you are a student with learning needs that require special accommodation, contact the Office of Disability Services at (404) 894-2563 or [disabilityservices.gatech.edu](http://disabilityservices.gatech.edu/), as soon as possible, to make an appointment to discuss your special needs and to obtain an accommodations letter. Please also e-mail me as soon as possible in order to set up a time to discuss your learning needs.


## Exam Procedures

Exams will be proctored live. You will be notified ahead of time for what devices and materials are allowed (if any) during exams.


## Missed Exams

- If you have a valid reason to request a make-up exam, please contact the instructor as early as possible. Only extraordinary cases (with proof) will be considered.

- In the case of SERIOUS illness, please contact the instructor BEFORE the exam and get a doctor’s note.

- In the case of emergency, please contact the Office of Dean of Students immediately.

- Requests for student organization excused absences must be made no later than two weeks prior to the date of the event. No late requests will be honored. Please have your advisor send me a written notice or an e-mail.


## Student-Faculty Expectations Agreement

At Georgia Tech we believe that it is important to strive for an atmosphere of mutual respect, acknowledgment, and responsibility between faculty members and the student body. See [catalog.gatech.edu/rules/22](http://www.catalog.gatech.edu/rules/22/) for an articulation of some basic expectation that you can have of me and that I have of you. In the end, simple respect for knowledge, hard work, and cordial interactions will help build the environment we seek. Therefore, I encourage you to remain committed to the ideals of Georgia Tech while in this class.

**My main rule is this**: if you put appropriate effort into this course, and are respectful of the time and effort your instructors, TAs, and classmates put in, I will always be willing to repay that respect in kind and help you succeed in any way I can.



# Additional Student Resources


## Mental Health Resources

All of us benefit from support during times of struggle. You are not alone. There are many helpful resources available on campus and an important part of the college experience is learning how to ask for help. Asking for support sooner rather than later is often helpful. If you or anyone you know experiences any academic stress, difficult life events, or feelings like anxiety or depression, we strongly encourage you to seek support. 

### Counseling Center

Smithgall Student Services Building, 2nd floor

404-894-2575

After hours counselor: 404-894-2204

Monday--Friday, 8am--5pm

[counseling.gatech.edu](http://counseling.gatech.edu)


## Personal Resources

### The Office of the Dean of Students

Smithgall Student Services Building, 2nd floor

404-894-6367

[studentlife.gatech.edu/content/services](http://studentlife.gatech.edu/content/services)

[gatech-advocate.symplicity.com/care_report/index.php/pid383662](https://gatech-advocate.symplicity.com/care_report/index.php/pid383662)

### Students’ Temporary Assistance and Resources (STAR)

Can assist with interview clothing, food, and housing needs.

[studentlife.gatech.edu/content/need-help](http://studentlife.gatech.edu/content/need-help)

### Stamps Health Services

Primary care, pharmacy, women’s health, psychiatry, immunization and allergy, health promotion, and nutrition

404-894-1420

[health.gatech.edu](https://health.gatech.edu)

### Women’s Resource Center

404-385-0230

[womenscenter.gatech.edu](http://www.womenscenter.gatech.edu)

### LGBTQIA Resource Center

404-385-2679

[lgbtqia.gatech.edu](http://lgbtqia.gatech.edu/)

### Veteran’s Resource Center

404-385-2067

[veterans.gatech.edu/](http://veterans.gatech.edu/)


## Academic Resources

### Center for Academic Success

[success.gatech.edu](http://success.gatech.edu)

[1-to-1 tutoring](http://success.gatech.edu/1-1-tutoring)

[Peer-Led Undergraduate Study (PLUS)](http://success.gatech.edu/tutoring/plus)

[Academic coaching](http://success.gatech.edu/coaching)

[Residence Life’s Learning Assistance Program](https://housing.gatech.edu/learningassistance-program)

[OMED: Educational Services](http://omed.gatech.edu/programs/academic-support), group study sessions and tutoring programs

[Communication Center](http://www.communicationcenter.gatech.edu), individualized help with writing and multimedia projects

Academic advisors for your major


## Software and IT help

#### Office of Information Technology

[oit.gatech.edu](https://www.oit.gatech.edu/)

404-385-1111

[support@cos.gatech.edu](mailto:support@cos.gatech.edu)

Free access to Microsoft Word at https://oit.gatech.edu/email

### Digital Reader Supports

[Beeline Reader](https://www.beelinereader.com/)

[Dyslexie Font](https://www.dyslexiefont.com/)


## Statement of Inclusivity

As a member of the Georgia Tech community, I am committed to creating a learning environment in which all of my students feel safe and included. Because we are individuals with varying needs, I am reliant on your feedback to achieve this goal. To that end, I invite you to enter into dialogue with me about the things I can stop, start, and continue doing to make my classroom an environment in which every student feels valued and can engage actively in our learning community.


## Health Protocol

Though it is unlikely, out of concern for the health of everyone, if the instructor becomes ill the in-person lectures or labs may move online for a period if necessary during the semester



# Class Schedule

| **Week of… / Suggested Reading**                                                                                    | **Tuesday**                                                     | **Thursday**                                | **Friday (Lab)**                               | **Homework**                                     |
| ------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------- | ------------------------------------------- | ---------------------------------------------- | ------------------------------------------------ |
| **1: August 24**<br>Lane Ch 1, Poldrack Ch 1–3                                                                      | Introduction                                                    | Exploring Data                              | Getting Started in R and Quarto                |                                                  |
| **2: August 31**<br>Lane Ch 5, Poldrack Ch 4, 6                                                                     | Visualizing Data                                                | Introduction to Probability                 | Data Visualization in ggplot2                  | **Assigned:** HW 1; Weeks 1 & 2                  |
| **3: September 7**<br>Lane Ch 7, 9, 17, Poldrack Ch 7, 8, [TBOB video](https://www.youtube.com/watch?v=zeJD6dqJ5lo) | Monte Carlo Simulation<br>Sampling Distributions                | Null Hypothesis Testing<br>Chi Square tests | Data Manipulation <br> Simulation              |                                                  |
| **4: September 14**<br>Lane Ch 11, 12, Poldrack Ch 9, 10                                                            | t-distribution<br>**POSIT CONFERENCE**                          | More t-distribution<br>Effect Size          | Chi Square Tests <br> T-tests <br> Effect size | **Due:** HW 1<br>**Assigned:** HW 2; Weeks 3 & 4 |
| **5: September 21**<br>Lane Ch 8, Poldrack Ch 5                                                                     | Power                                                           | Statistical Models                          | Power Analysis and Cross Validation            |                                                  |
| **6: September 28**                                                                                                 | Review 1                                                        | Midterm 1                                   | Functional Programming                         |                                                  |
| **7: October 5**<br>Poldrack Ch 11                                                                                  | FALL BREAK                                                      | Primer on Likelihood<br>Intro to Bayes      | Bayesian Inference (LECTURE)                   | **Due:** HW 2<br>**Assigned:** HW 3; Weeks 5 & 7 |
| **8: October 12**<br>Poldrack Ch 15, Lane Ch 15 (1–5)                                                               | Bayesian t-tests and diagnostics (LAB)                          | One way ANOVA                               | Frequentist and Bayesian Comparison of ANOVA   |                                                  |
| **9: October 19**<br>Navarro Ch 14, Lane Ch 15 (6–8)                                                                | Comparisons and Contrasts                                       | Factorial ANOVA                             | Estimated Marginal means (emmeans)             | **Due:** HW 3<br>**Assigned:** HW 4              |
| **10: October 26**<br>Rest of Lane Ch 15                                                                            | Unequal Sample sizes in factorial ANOVA and simple main effects | Review 2                                    | Factorial ANOVA                                |                                                  |
| **11: November 2**<br>Crump Ch 8                                                                                    | Midterm 2                                                       | Repeated Measures                           | Repeated Measures ANOVA                        | **Assigned:** HW 5                               |
| **12: November 9**<br>Poldrack Ch 13, Lane Ch 14, Crump Ch 3, Barr Ch 2                                             | Correlation<br>Visualizing Multiple Variables                   | Simple Regression                           | Scatterplots and Scatterplot Matrices          | **Due:** HW 4                                    |
| **13: November 16**<br>Poldrack Ch 14, Lane Ch 19, Barr Ch 3                                                        | Intro to multiple linear regression                             | Effect size and assumption checking         | NO CLASS (Mark and Jess at Conference)         | **Due:** HW 5<br>**Assigned:** HW 6              |
| **14: November 23**                                                                                                 | Regression (LAB)                                                | THANKSGIVING                                | THANKSGIVING                                   |                                                  |
| **15: November 30**<br>Nguyen Ch 9, 10, Barr Ch 4                                                                   | Moderation Models                                               | Mediation Models                            | Moderation and Mediation                       | **Due:** HW 6                                    |
| **16: December 7**                                                                                                  | Review 3                                                        | **NO CLASSES**                              |                                                | **Due:** Lab Project                             |
| **17: December 14**                                                                                                 | **FINAL EXAM 2:40pm**                                           |                                             |                                                |                                                  |

