{
  "hash": "503fb782e3db080cb438d51cc1cc5887",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bayesian *t*-Tests and Diagnostics\"\nsubtitle: \"PSYC 6019-A01 / PSYC 6022-A01 <br> 2025-10-13 | Lab 7\"\nauthor: \"Jess Helmer\"\nfooter: \"[jhelmer3.github.io/PSYC6019-2026](https://jhelmer3.github.io/PSYC6019-2026/)\"\nformat: \n  revealjs:\n    code-link: true\n    slide-number: true\n    code-line-numbers: false\n    theme: ../../gt-theme.scss\n    width: 1200\nexecute: \n  echo: true\n  dpi: 600\n  freeze: auto\nknitr:\n  opts_chunk:\n    dev: svg\nresources:\n  - ../media/lab_07/samples.mp4\n---\n\n## Outline\n\n- *t*-tests as linear models\n\n- Bayesian *t*-tests\n\n- Diagnostics\n\n\n::: {.cell}\n\n:::\n\n\n\n\n# *t*-Tests as a Linear Model\n\n\n## *t*-Tests as a Linear Model\n\nWe can specify a *t*-test as a linear model.\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nOur goal with *t*-tests is to compare means.\n\n$H_0$: $\\mu_1 = \\mu_2$ aka $\\mu_1 - \\mu_2 = 0$\n:::\n\n::: {.column width=\"50%\"}\nWe can estimate the overall mean of the outcome with an intercept-only model, where $\\beta_0$ is the intercept.\n\n$y = \\beta_0 + \\epsilon$\n\nThen, we can add a slope term $\\beta_1$ to represent the difference in means between groups.\n\n$y = \\beta_0 + \\beta_1 \\times \\text{group} + \\epsilon$\n:::\n::::\n\n\n## *t*-Tests as a Linear Model\n\nTogether, these parameters contain us the same information as a *t*-test.\n\nFor example, in an experiment, if the control group is coded $\\text{group}_\\text{control} = 0$ and the treatment group is coded $\\text{group}_\\text{control} = 1$,\n\n::: subpoint\n○ $\\beta_0 =$ mean of control group\n:::\n\n::: subpoint\n○ $\\beta_1 =$ difference in means between control group and treatment group\n:::\n\n::: subpoint\n○ $\\beta_0 + \\beta_1 =$ mean of treatment group\n:::\n\n\n\n# Bayesian *t*-Tests\n\n\n## Bayesian Inference\n\nSo far, we've been working with the frequentist statistical framework, Null Hypothesis Significance Testing (NHST).\n\n:::: {.columns style=\"font-size:80%\"}\n::: {.column width=\"50%\"}\n**Frequentist**\n\nIn NHST, we speak only about *likelihoods*. The probability that we would have observed our data $D$ (or more extreme data) given some null hypothesis parameter $\\theta$\n\nE.g., the probability that we would observe a mean difference on a test of $\\bar{x}_\\text{treatment} - \\bar{x}_\\text{control} = 5$ points given the true mean difference in the population is $\\bar{x}_\\text{treatment} - \\bar{x}_\\text{control} = 0$.\n\n$P(D | \\theta)$\n:::\n\n::: {.column width=\"50%\"}\n**Bayesian**\n\nWhat we as researchers are often more interested in is the probability that a parameter $\\theta$ is the true parameter given data $D$ we have observed.\n\nE.g., given that we have observed a mean difference of $\\bar{x}_\\text{treatment} - \\bar{x}_\\text{control} = 5$, what is the probability that the true mean difference is $\\bar{x}_\\text{treatment} - \\bar{x}_\\text{control} = 0$? What is the probability that the true mean difference is $\\bar{x}_\\text{treatment} - \\bar{x}_\\text{control} = 5$?\n\n$P(\\theta | D)$\n:::\n::::\n\n\n## Bayesian Inference\n\nIn order to get $P(\\theta | D)$, we need Bayes' Rule. \n\n$$ P(\\theta | D) = \\frac{ P(\\theta) P(D | \\theta) }{ P(D) } $$\n\n::: subpoint\n○ $P(\\theta | D) =$ *posterior* distribution, this is what we want to create!\n:::\n\n::: subpoint\n○ $P(\\theta)$ *prior* distribution, information we know about $\\theta$ before seeing $D$\n:::\n\n::: subpoint\n○ $P(D | \\theta)$ likelihood, the same as before\n:::\n\n::: subpoint\n○ $P(D)$ scaling term, brings everything back down to probability scale. Makes Bayes analytic calulations mathematically challenging / impossible! \n:::\n\n::: fragment\nMotivates *sampling* from the posterior distribution, instead of calculating it.\n:::\n\n\n## Getting to the Posterior\n\nOur goal in Bayes is to estimate $P(\\theta | D) = \\frac{P(\\theta) P(D | \\theta)}{P(D)} = \\frac{\\text{prior} \\times \\text{likelihood}}{\\text{scaling term}}$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-1-1.svg){fig-align='center' width=480}\n:::\n:::\n\n\n\n## Getting to the Posterior\n\nOur goal in Bayes is to estimate $P(\\theta | D) = \\frac{P(\\theta) P(D | \\theta)}{P(D)}$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-2-1.svg){fig-align='center' width=480}\n:::\n:::\n\n\n\n\n## Getting to the Posterior\n\nOur goal in Bayes is to estimate $P(\\theta | D) = \\frac{P(\\theta) P(D | \\theta)}{P(D)}$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-3-1.svg){fig-align='center' width=480}\n:::\n:::\n\n\n\n## Getting to the Posterior\n\nOur goal in Bayes is to estimate $P(\\theta | D) = \\frac{P(\\theta) P(D | \\theta)}{P(D)}$.\n\n<!-- But most of the time, $P(\\theta | D)$ is too complex to solve analytically.  -->\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-4-1.svg){fig-align='center' width=480}\n:::\n:::\n\n\n\n## Getting to the Posterior\n\nOur goal in Bayes is to estimate $P(\\theta | D) = \\frac{P(\\theta) P(D | \\theta)}{P(D)}$.\n\n<!-- But most of the time, $P(\\theta | D)$ is too complex to solve analytically.  -->\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-5-1.svg){fig-align='center' width=480}\n:::\n:::\n\n\n\n## Getting to the Posterior\n\nOur goal in Bayes is to estimate $P(\\theta | D) = \\frac{P(\\theta) P(D | \\theta)}{P(D)}$.\n\n<!-- {{ video ../media/lab_07/samples.mp4 }} -->\n\n::: {.absolute left=\"15.1%\" bottom=\"-2%\" width=\"880\" height=\"528\"}\n<video src=\"../media/lab_07/samples.mp4\"\n       style=\"width:100%; height:100%; object-fit:contain; display:block; background:white;\"\n       controls></video>\n:::\n\n\n## Getting to the Posterior\n\nHow can we sample from posterior distributions? We can use a *probabalistic programming language*.\n\n:::: {.columns}\n::: {.column width=\"33%\"}\n![](https://mc-stan.org/docs/img/logo_tm.png)\n:::\n\n::: {.column width=\"66%\"}\n*Stan* is an open-source probabalistic programming language that's widely used to write Bayesian models.\n\nIt has a well-developed, user-friendly R interface called `{rstanarm}`, which we will use!\n\n::: subpoint-narrow\n○ Means we can start to work with Bayesian models without having to lean the Stan language itself\n:::\n:::\n::::\n\n\n## Bayesian *t*-Tests\n\nA very user-friendly interface to Bayesian models with `Stan` is the `{rstanarm}` R package!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"rstanarm\")\nlibrary(rstanarm)\n\n# options(mc.cores = parallel::detectCores())\n\nfiltered_mpg <- mpg |>\n  filter(when_any(cyl == 4, cyl == 8)) |>\n  mutate(cyl = factor(cyl))\n```\n:::\n\n\n\n## Bayesian *t*-Tests\n\nA very user-friendly interface to Bayesian models with `Stan` is the `{rstanarm}` R package!\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq_t_test <- t.test(hwy ~ cyl, data = filtered_mpg)\nfreq_t_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  hwy by cyl\nt = 17.586, df = 144.65, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group 4 and group 8 is not equal to 0\n95 percent confidence interval:\n  9.918065 12.429731\nsample estimates:\nmean in group 4 mean in group 8 \n       28.80247        17.62857 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_t_test <- stan_glm(hwy ~ cyl, data = filtered_mpg,\n                         family = \"gaussian\")\nsummary(bayes_t_test)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       gaussian [identity]\n formula:      hwy ~ cyl\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 151\n predictors:   2\n\nEstimates:\n              mean   sd    10%   50%   90%\n(Intercept)  28.8    0.4  28.2  28.8  29.4\ncyl8        -11.2    0.7 -12.0 -11.2 -10.3\nsigma         4.0    0.2   3.7   4.0   4.3\n\nFit Diagnostics:\n           mean   sd   10%   50%   90%\nmean_PPD 23.6    0.5 23.0  23.6  24.2 \n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n              mcse Rhat n_eff\n(Intercept)   0.0  1.0  3794 \ncyl8          0.0  1.0  3909 \nsigma         0.0  1.0  3197 \nmean_PPD      0.0  1.0  3413 \nlog-posterior 0.0  1.0  1719 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n:::\n::::\n\n\n## Bayesian *t*-Tests\n\nA very user-friendly interface to Bayesian models with `Stan` is the `{rstanarm}` R package!\n\n:::: {.columns style=\"font-size:80%\"}\n::: {.column width=\"50%\"}\n`summary()` function contains lots of information about the model:\n\n::: subpoint-narrow\n○ `Estimates`: means, SDs, and quantiles (can specify with `probs`) for each parameter.\n:::\n\n::: subpoint-narrow\n○ `Fit Diagnostics`: `mean_PPD` mean of the posterior distribution of the outcome. If `mean_PPD` is very different from what you'd expect the mean of the outcome variable to be, may be an indicator of something being wrong.\n:::\n\n::: subpoint-narrow\n○ `MCMC Diagnostics`: Diagnostics for the Markov Chain Monte Carlo sampler (more on this later).\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_t_test <- stan_glm(hwy ~ cyl, data = filtered_mpg,\n                         family = \"gaussian\")\nsummary(bayes_t_test, probs = c(0.05, 0.5, 0.95))\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       gaussian [identity]\n formula:      hwy ~ cyl\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 151\n predictors:   2\n\nEstimates:\n              mean   sd    5%    50%   95%\n(Intercept)  28.8    0.4  28.1  28.8  29.5\ncyl8        -11.2    0.7 -12.3 -11.2 -10.1\nsigma         4.0    0.2   3.7   4.0   4.4\n\nFit Diagnostics:\n           mean   sd   5%   50%   95%\nmean_PPD 23.6    0.5 22.9 23.6  24.4 \n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n              mcse Rhat n_eff\n(Intercept)   0.0  1.0  3501 \ncyl8          0.0  1.0  4114 \nsigma         0.0  1.0  3671 \nmean_PPD      0.0  1.0  3861 \nlog-posterior 0.0  1.0  1793 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n:::\n::::\n\n\n## Bayesian *t*-Tests\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_summary(bayes_t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPriors for model 'bayes_t_test' \n------\nIntercept (after predictors centered)\n  Specified prior:\n    ~ normal(location = 24, scale = 2.5)\n  Adjusted prior:\n    ~ normal(location = 24, scale = 17)\n\nCoefficients\n  Specified prior:\n    ~ normal(location = 0, scale = 2.5)\n  Adjusted prior:\n    ~ normal(location = 0, scale = 34)\n\nAuxiliary (sigma)\n  Specified prior:\n    ~ exponential(rate = 1)\n  Adjusted prior:\n    ~ exponential(rate = 0.15)\n------\nSee help('prior_summary.stanreg') for more details\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n`{rstanarm}` generally defines priors on the *z*-scale (\"specified prior\") and then transforms them to the scale of our variables (\"adjusted prior\") to actually run the model.\n\nThe \"adjusted prior\" is what was actually used.\n:::\n::::\n\n\n## Full Model\n\n$$\n\\begin{aligned}\n\\text{highway MPG}_i &= \\beta_0 + \\beta_1 \\text{cylinders}_i + \\epsilon_i && \\text{likelihood: a linear model} \\\\\n\\beta_0 &\\sim N(24, 17) && \\text{prior for intercept} \\\\\n\\beta_1 &\\sim N(0, 8.6) && \\text{prior for slope} \\\\\n\\epsilon &\\sim \\text{Exponential}(0.15)  && \\text{prior for residual variance}\n\\end{aligned}\n$$\n\n\n## Visualizing Results\n\nThe `bayesplot` package provides many helpful functions for plotting results of a Bayesian model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"bayesplot\")\nlibrary(bayesplot)\n```\n:::\n\n\n\n<!-- ## Visualizing Results -->\n\n<!-- ::: {.panel-tabset} -->\n<!-- ### Plot -->\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-width: 5 -->\n<!-- #| fig-height: 4 -->\n<!-- #| fig-align: center -->\n\n<!-- ppc_dens_overlay( -->\n<!--   y = filtered_mpg$hwy, -->\n<!--   yrep = posterior_predict(bayes_t_test, draws = 50) -->\n<!-- ) -->\n<!-- ``` -->\n\n<!-- ### Code -->\n<!-- ```{r} -->\n<!-- #| eval: false -->\n<!-- ppc_dens_overlay( -->\n<!--   y = filtered_mpg$hwy, -->\n<!--   yrep = posterior_predict(bayes_t_test, draws = 50) -->\n<!-- ) -->\n<!-- ``` -->\n<!-- ::: -->\n\n\n<!-- ## Visualizing Results -->\n\n<!-- ::: {.panel-tabset} -->\n<!-- ### Plot -->\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-width: 9 -->\n<!-- #| fig-height: 4 -->\n<!-- #| fig-align: center -->\n\n<!-- bayesplot::ppc_dens_overlay_grouped( -->\n<!--   y = filtered_mpg$hwy, -->\n<!--   yrep = posterior_predict(bayes_t_test, draws = 50), -->\n<!--   group = filtered_mpg$cyl -->\n<!-- ) -->\n<!-- ``` -->\n\n<!-- ### Code -->\n<!-- ```{r} -->\n<!-- #| eval: false -->\n<!-- bayesplot::ppc_dens_overlay_grouped( -->\n<!--   y = filtered_mpg$hwy, -->\n<!--   yrep = posterior_predict(bayes_t_test, draws = 50), -->\n<!--   group = filtered_mpg$cyl -->\n<!-- ) -->\n<!-- ``` -->\n<!-- ::: -->\n\n\n## Visualizing Results\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nWe can check how well our observed data ($y$) compare to the fitted model's predictions ($y_{rep}$).\n:::\n\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-14-1.svg){fig-align='center' width=480}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nbayesplot::ppc_violin_grouped(\n  y = filtered_mpg$hwy,\n  yrep = posterior_predict(bayes_t_test, draws = 50),\n  group = filtered_mpg$cyl\n)\n```\n:::\n\n:::\n:::\n::::\n\n\n\n## Visualizing Results\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nWe can check how well our observed data ($y$) compare to the fitted model's predictions ($y_{rep}$).\n\nAnd layer on `geom`s like a regular `ggplot`.\n:::\n\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-16-1.svg){fig-align='center' width=480}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nbayesplot::ppc_violin_grouped(\n  y = filtered_mpg$hwy,\n  yrep = posterior_predict(bayes_t_test, draws = 50),\n  group = filtered_mpg$cyl\n) +\n  geom_jitter(data = filtered_mpg,\n              aes(y = hwy, x = cyl),\n              alpha = 0.3,\n              color = \"#011f4b\",\n              inherit.aes = F)\n```\n:::\n\n:::\n:::\n::::\n\n\n\n\n\n\n<!-- ## Prior Implications -->\n\n<!-- :::: {.columns} -->\n<!-- ::: {.column width=\"50%\"} -->\n<!-- Given that the distribution of the outcome following just the priors includes negative values for highway MPG, maybe we can afford to narrow them a bit! -->\n\n<!-- And maybe we want to be a little more skeptical of large effects, so we can narrow the prior on the slope, too. -->\n<!-- ::: -->\n\n<!-- ::: {.column width=\"50%\"} -->\n\n<!-- ::: {.panel-tabset} -->\n<!-- ### Plot -->\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-width: 5.5 -->\n<!-- #| fig-height: 2.5 -->\n<!-- #| fig-align: center -->\n<!-- t_test_from_prior_only <- stan_glm( -->\n<!--   hwy ~ cyl, data = filtered_mpg, -->\n<!--   family = \"gaussian\", refresh = 0, -->\n<!--   prior_PD = T -->\n<!-- ) -->\n<!-- ppc_dens_overlay_grouped( -->\n<!--   y = filtered_mpg$hwy,  -->\n<!--   yrep = posterior_predict(t_test_from_prior_only, draws = 50), -->\n<!--   group = filtered_mpg$cyl -->\n<!-- ) -->\n<!-- ``` -->\n\n<!-- ### Code -->\n<!-- ```{r} -->\n<!-- #| eval: false -->\n<!-- t_test_from_prior_only <- stan_glm( -->\n<!--   hwy ~ cyl, data = filtered_mpg, -->\n<!--   family = \"gaussian\", refresh = 0, -->\n<!--   prior_PD = T -->\n<!-- ) -->\n<!-- ppc_dens_overlay_grouped( -->\n<!--   y = filtered_mpg$hwy,  -->\n<!--   yrep = posterior_predict(t_test_from_prior_only, draws = 50), -->\n<!--   group = filtered_mpg$cyl -->\n<!-- ) -->\n<!-- ``` -->\n<!-- ::: -->\n\n\n<!-- ::: -->\n<!-- :::: -->\n\n\n## Changing Priors\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Original Model**\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_summary(bayes_t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPriors for model 'bayes_t_test' \n------\nIntercept (after predictors centered)\n  Specified prior:\n    ~ normal(location = 24, scale = 2.5)\n  Adjusted prior:\n    ~ normal(location = 24, scale = 17)\n\nCoefficients\n  Specified prior:\n    ~ normal(location = 0, scale = 2.5)\n  Adjusted prior:\n    ~ normal(location = 0, scale = 34)\n\nAuxiliary (sigma)\n  Specified prior:\n    ~ exponential(rate = 1)\n  Adjusted prior:\n    ~ exponential(rate = 0.15)\n------\nSee help('prior_summary.stanreg') for more details\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column style=\"font-size:80%\" width=\"50%\"}\n**Changing Priors**\n\n`{rstanarm}` generally defines priors on the *z*-scale (\"specified prior\") and then transforms them to the scale of our variables (\"adjusted prior\") to actually run the model.\n\nThe \"adjusted prior\" is what was actually used.\n\nWe can choose to specify a prior on the *z*-scale (`autoscale = T`) or as-is (default) (example on next slide).\n:::\n::::\n\n\n## Changing Priors\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Original Model**\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_summary(bayes_t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPriors for model 'bayes_t_test' \n------\nIntercept (after predictors centered)\n  Specified prior:\n    ~ normal(location = 24, scale = 2.5)\n  Adjusted prior:\n    ~ normal(location = 24, scale = 17)\n\nCoefficients\n  Specified prior:\n    ~ normal(location = 0, scale = 2.5)\n  Adjusted prior:\n    ~ normal(location = 0, scale = 34)\n\nAuxiliary (sigma)\n  Specified prior:\n    ~ exponential(rate = 1)\n  Adjusted prior:\n    ~ exponential(rate = 0.15)\n------\nSee help('prior_summary.stanreg') for more details\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n**Changing Priors**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_t_test_v2 <- stan_glm(\n  hwy ~ cyl, data = filtered_mpg,\n  prior = normal(0, 1.5, autoscale = T),\n  prior_intercept = normal(24, 15),\n  family = \"gaussian\"\n)\nsummary(bayes_t_test_v2, probs = c(0.05, 0.5, 0.95))\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 1).\nChain 1: \nChain 1: Gradient evaluation took 1.6e-05 seconds\nChain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.16 seconds.\nChain 1: Adjust your expectations accordingly!\nChain 1: \nChain 1: \nChain 1: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 1: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 1: \nChain 1:  Elapsed Time: 0.039 seconds (Warm-up)\nChain 1:                0.065 seconds (Sampling)\nChain 1:                0.104 seconds (Total)\nChain 1: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 2).\nChain 2: \nChain 2: Gradient evaluation took 1e-05 seconds\nChain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.1 seconds.\nChain 2: Adjust your expectations accordingly!\nChain 2: \nChain 2: \nChain 2: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 2: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 2: \nChain 2:  Elapsed Time: 0.069 seconds (Warm-up)\nChain 2:                0.06 seconds (Sampling)\nChain 2:                0.129 seconds (Total)\nChain 2: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 3).\nChain 3: \nChain 3: Gradient evaluation took 1e-05 seconds\nChain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.1 seconds.\nChain 3: Adjust your expectations accordingly!\nChain 3: \nChain 3: \nChain 3: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 3: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 3: \nChain 3:  Elapsed Time: 0.038 seconds (Warm-up)\nChain 3:                0.076 seconds (Sampling)\nChain 3:                0.114 seconds (Total)\nChain 3: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 4).\nChain 4: \nChain 4: Gradient evaluation took 1.4e-05 seconds\nChain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.14 seconds.\nChain 4: Adjust your expectations accordingly!\nChain 4: \nChain 4: \nChain 4: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 4: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 4: \nChain 4:  Elapsed Time: 0.055 seconds (Warm-up)\nChain 4:                0.061 seconds (Sampling)\nChain 4:                0.116 seconds (Total)\nChain 4: \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       gaussian [identity]\n formula:      hwy ~ cyl\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 151\n predictors:   2\n\nEstimates:\n              mean   sd    5%    50%   95%\n(Intercept)  28.8    0.5  28.0  28.8  29.5\ncyl8        -11.2    0.7 -12.2 -11.2 -10.1\nsigma         4.0    0.2   3.6   4.0   4.4\n\nFit Diagnostics:\n           mean   sd   5%   50%   95%\nmean_PPD 23.6    0.5 22.8 23.6  24.4 \n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n              mcse Rhat n_eff\n(Intercept)   0.0  1.0  3469 \ncyl8          0.0  1.0  3757 \nsigma         0.0  1.0  3676 \nmean_PPD      0.0  1.0  3932 \nlog-posterior 0.0  1.0  1879 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n:::\n::::\n\n\n<!-- ## Prior Implications -->\n\n<!-- :::: {.columns} -->\n<!-- ::: {.column width=\"50%\"} -->\n<!-- Implications of our new priors. -->\n<!-- ::: -->\n\n<!-- ::: {.column width=\"50%\"} -->\n\n<!-- ::: {.panel-tabset} -->\n<!-- ### Plot -->\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-width: 5.5 -->\n<!-- #| fig-height: 2.5 -->\n<!-- #| fig-align: center -->\n<!-- t_test_from_prior_only_v2 <- stan_glm( -->\n<!--   hwy ~ cyl, data = filtered_mpg, -->\n<!--   family = \"gaussian\", refresh = 0, -->\n<!--   prior = normal(0, 1, autoscale = T), -->\n<!--   prior_intercept = normal(24, 4), -->\n<!--   prior_PD = T -->\n<!-- ) -->\n<!-- ppc_dens_overlay_grouped( -->\n<!--   y = filtered_mpg$hwy,  -->\n<!--   yrep = posterior_predict(t_test_from_prior_only_v2, draws = 50), -->\n<!--   group = filtered_mpg$cyl -->\n<!-- ) -->\n<!-- ``` -->\n\n<!-- ### Code -->\n<!-- ```{r} -->\n<!-- #| eval: false -->\n<!-- t_test_from_prior_only_v2 <- stan_glm( -->\n<!--   hwy ~ cyl, data = filtered_mpg, -->\n<!--   family = \"gaussian\", refresh = 0, -->\n<!--   prior = normal(0, 1, autoscale = T), -->\n<!--   prior_intercept = normal(24, 4), -->\n<!--   prior_PD = T -->\n<!-- ) -->\n<!-- ppc_dens_overlay_grouped( -->\n<!--   y = filtered_mpg$hwy,  -->\n<!--   yrep = posterior_predict(t_test_from_prior_only_v2, draws = 50), -->\n<!--   group = filtered_mpg$cyl -->\n<!-- ) -->\n<!-- ``` -->\n<!-- ::: -->\n\n\n<!-- ::: -->\n<!-- :::: -->\n\n\n## Credible Intervals\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Equal Tailed Interval**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_interval(bayes_t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   5%        95%\n(Intercept)  28.09314  29.524566\ncyl8        -12.26172 -10.129312\nsigma         3.66012   4.383342\n```\n\n\n:::\n:::\n\n\nCan also get ETIs from the `summary()` function, as before.\n:::\n\n::: {.column width=\"50%\"}\n\n**Highest Density Interval**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"bayestestR\")\nbayestestR::hdi(bayes_t_test, component = \"all\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHighest Density Interval\n\nParameter   |         95% HDI\n-----------------------------\n(Intercept) | [ 27.98, 29.69]\ncyl8        | [-12.44, -9.90]\n\n# Fixed effects (sigma)\n\nParameter |         95% HDI\n---------------------------\nsigma     | [  3.60,  4.48]\n```\n\n\n:::\n:::\n\n:::\n::::\n\n\n<!-- ```{r} -->\n<!-- etis <- posterior_interval(bayes_t_test) |> -->\n<!--   as.data.frame() -->\n<!-- hdpis <- bayestestR::hdi(bayes_t_test, component = \"all\") |> -->\n<!--   as.data.frame() -->\n\n\n<!-- bayes_t_test |> -->\n<!--   bayesplot::mcmc_dens(pars = c(\"(Intercept)\")) + -->\n<!--   geom_vline(aes(xintercept = etis[\"(Intercept)\", \"5%\"])) + -->\n<!--   geom_vline(aes(xintercept = etis[\"(Intercept)\", \"95%\"])) + -->\n<!--   # geomtextpath::geom_textsegment(aes(x = etis[\"(Intercept)\", \"5%\"], xend = etis[\"(Intercept)\", \"95%\"],  -->\n<!--   #                                    y = Inf, yend = Inf, label = \"90% CTI\", vjust = 1)) + -->\n<!--   geom_rect(aes(xmin = hdpis[hdpis$Parameter == \"(Intercept)\", \"CI_low\"], xmax = hdpis[hdpis$Parameter == \"(Intercept)\", \"CI_high\"], ymin = 0, ymax = 0.5), alpha = 0.3, fill = \"pink\") -->\n<!--   geom_vline(aes(xintercept = hdpis[hdpis$Parameter == \"(Intercept)\", \"CI_low\"])) + -->\n<!--   geom_vline(aes(xintercept = hdpis[hdpis$Parameter == \"(Intercept)\", \"CI_high\"])) + -->\n<!--   geomtextpath::geom_textsegment(aes(x = hdpis[hdpis$Parameter == \"(Intercept)\", \"CI_low\"], xend = hdpis[hdpis$Parameter == \"(Intercept)\", \"CI_high\"],  -->\n<!--                                      y = Inf, yend = Inf, label = \"90% HDPI\", vjust = 1)) -->\n<!-- ``` -->\n\n# Diagnostics\n\n\n## Diagnostics\n\nOur goal in Bayes is to estimate $P(\\theta | D) = \\frac{P(\\theta) P(D | \\theta)}{P(D)} = \\frac{\\text{prior} \\times \\text{likelihood}}{\\text{scaling term}}$.\n\nBut most of the time, $P(\\theta | D)$ is too complex to solve analytically. So, we estimate Bayesian models by drawing **samples** from the posterior with Markov Chain Monte Carlo (MCMC).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-24-1.svg){fig-align='center' width=480}\n:::\n:::\n\n\n\n\n## Diagnostics with Bayes\n\nBut most of the time, $P(\\theta | D)$ is too complex to solve analytically. So, we estimate Bayesian models with Markov Chain Monte Carlo (MCMC).\n\n[The job of MCMC is to explore and sample from the posterior probability distribution $P(\\theta | D)$ for all $\\theta$ at a rate proportional to each probability.]{.fragment}\n\n[So, after many MCMC samples, we end up with a density distribution of samples with height matching $P(\\theta | D)$, and we can use those samples to make inferences about our parameters and outcomes!]{.fragment}\n\n::: {.subpoint .fragment}\n○ E.g., we believe there is a 90% chance the difference in highway MPG between four- and eight-cylinder cars is within the interval [-12.26, -10.13].\n:::\n\n[But, all this hinges on the MCMC sampler---we have to check it for evidence that it *sampled well*.]{.fragment}\n\n\n## Looking at the Samples\n\nOften, a good first step for checking the sampler is just looking at what it sampled!\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n[This is called a *trace plot*. It shows the samplers' samples for each iteration it runs. Can you tell if this sampler sampled well?]{.fragment fragment-index=2}\n:::\n\n::: {.column width=\"50%\"}\n::: {.fragment fragment-index=1}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-25-1.svg){fig-align='center' width=576}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nscale_colors <-  c(\"steelblue\", \"#D98282\", \"#6BAE9D\", \"#8C7AAE\")\nx <- bayesplot::example_mcmc_draws(chains = 1, params = 1)\nbayesplot::mcmc_trace(x) +\n  scale_color_manual(values = scale_colors)\n```\n:::\n\n:::\n:::\n:::\n::::\n\n\n## Looking at the Samples\n\nOften, a good first step for checking the sampler is just looking at what it sampled!\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nWhat if I told you we ran another, completely separate run, and its samples looked like this?\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-27-1.svg){fig-align='center' width=576}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- bayesplot::example_mcmc_draws(chains = 2, params = 1)\nbayesplot::mcmc_trace(x) +\n  scale_color_manual(values = scale_colors) +\n  guides(color = guide_none())\n```\n:::\n\n:::\n:::\n::::\n\n\n## Looking at the Samples\n\nOften, a good first step for checking the sampler is just looking at what it sampled!\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nOr a third?\n:::\n\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-29-1.svg){fig-align='center' width=576}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- bayesplot::example_mcmc_draws(chains = 3, params = 1)\nbayesplot::mcmc_trace(x) +\n  scale_color_manual(values = scale_colors) +\n  guides(color = guide_none())\n```\n:::\n\n:::\n:::\n::::\n\n\n## Looking at the Samples\n\nOften, a good first step for checking the sampler is just looking at what it sampled!\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nA fourth? How much confidence do you have in the sampler now?\n\n[Looking at traceplots cannot guarantee the sampler is **correctly** sampling from the distribution, but if we run multiple *chains* (separate runs of MCMC, each doing their own thing independently), we can at least check if the sampler is sampling **consistently**.]{.fragment}\n:::\n\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-31-1.svg){fig-align='center' width=576}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- bayesplot::example_mcmc_draws(chains = 4, params = 1)\nbayesplot::mcmc_trace(x) +\n  scale_color_manual(values = scale_colors) +\n  guides(color = guide_none())\n```\n:::\n\n:::\n:::\n::::\n\n\n## Looking at the Samples\n\nOur example's trace plots! Also from `bayesplot`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_trace(bayes_t_test_v2)\n```\n\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-33-1.svg){width=1152}\n:::\n:::\n\n\n[Good! They look like \"fuzzy caterpillars.\"]{.fragment} [What does a bad chain look like?]{.fragment}\n\n\n<!-- ## Trace Rank Plots -->\n\n<!-- These are called \"trace rank\" plots. They're very similar to trace plots, except they *order* the samples in magnitude. Want to see all chains (colors) equally represented across the x-axis. -->\n\n<!-- It's mostly personal preference, but these are sometimes easier to see bad chains. -->\n\n<!-- ```{r} -->\n<!-- #| fig-height: 3 -->\n<!-- #| fig-width: 12 -->\n<!-- mcmc_rank_overlay(bayes_t_test_v2) -->\n<!-- ``` -->\n\n\n## Bad Sampling Example\n\nMessing with the algorithm on purpose to make it sample poorly...\n\n:::: {.columns}\n::: {.column width=\"90%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 1).\nChain 1: \nChain 1: Gradient evaluation took 2.3e-05 seconds\nChain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.23 seconds.\nChain 1: Adjust your expectations accordingly!\nChain 1: \nChain 1: \nChain 1: Iteration:    1 / 1200 [  0%]  (Warmup)\nChain 1: Iteration:  120 / 1200 [ 10%]  (Warmup)\nChain 1: Iteration:  201 / 1200 [ 16%]  (Sampling)\nChain 1: Iteration:  320 / 1200 [ 26%]  (Sampling)\nChain 1: Iteration:  440 / 1200 [ 36%]  (Sampling)\nChain 1: Iteration:  560 / 1200 [ 46%]  (Sampling)\nChain 1: Iteration:  680 / 1200 [ 56%]  (Sampling)\nChain 1: Iteration:  800 / 1200 [ 66%]  (Sampling)\nChain 1: Iteration:  920 / 1200 [ 76%]  (Sampling)\nChain 1: Iteration: 1040 / 1200 [ 86%]  (Sampling)\nChain 1: Iteration: 1160 / 1200 [ 96%]  (Sampling)\nChain 1: Iteration: 1200 / 1200 [100%]  (Sampling)\nChain 1: \nChain 1:  Elapsed Time: 0.007 seconds (Warm-up)\nChain 1:                0.058 seconds (Sampling)\nChain 1:                0.065 seconds (Total)\nChain 1: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 2).\nChain 2: \nChain 2: Gradient evaluation took 2.1e-05 seconds\nChain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.21 seconds.\nChain 2: Adjust your expectations accordingly!\nChain 2: \nChain 2: \nChain 2: Iteration:    1 / 1200 [  0%]  (Warmup)\nChain 2: Iteration:  120 / 1200 [ 10%]  (Warmup)\nChain 2: Iteration:  201 / 1200 [ 16%]  (Sampling)\nChain 2: Iteration:  320 / 1200 [ 26%]  (Sampling)\nChain 2: Iteration:  440 / 1200 [ 36%]  (Sampling)\nChain 2: Iteration:  560 / 1200 [ 46%]  (Sampling)\nChain 2: Iteration:  680 / 1200 [ 56%]  (Sampling)\nChain 2: Iteration:  800 / 1200 [ 66%]  (Sampling)\nChain 2: Iteration:  920 / 1200 [ 76%]  (Sampling)\nChain 2: Iteration: 1040 / 1200 [ 86%]  (Sampling)\nChain 2: Iteration: 1160 / 1200 [ 96%]  (Sampling)\nChain 2: Iteration: 1200 / 1200 [100%]  (Sampling)\nChain 2: \nChain 2:  Elapsed Time: 0.003 seconds (Warm-up)\nChain 2:                0.044 seconds (Sampling)\nChain 2:                0.047 seconds (Total)\nChain 2: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 3).\nChain 3: \nChain 3: Gradient evaluation took 1.2e-05 seconds\nChain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.12 seconds.\nChain 3: Adjust your expectations accordingly!\nChain 3: \nChain 3: \nChain 3: Iteration:    1 / 1200 [  0%]  (Warmup)\nChain 3: Iteration:  120 / 1200 [ 10%]  (Warmup)\nChain 3: Iteration:  201 / 1200 [ 16%]  (Sampling)\nChain 3: Iteration:  320 / 1200 [ 26%]  (Sampling)\nChain 3: Iteration:  440 / 1200 [ 36%]  (Sampling)\nChain 3: Iteration:  560 / 1200 [ 46%]  (Sampling)\nChain 3: Iteration:  680 / 1200 [ 56%]  (Sampling)\nChain 3: Iteration:  800 / 1200 [ 66%]  (Sampling)\nChain 3: Iteration:  920 / 1200 [ 76%]  (Sampling)\nChain 3: Iteration: 1040 / 1200 [ 86%]  (Sampling)\nChain 3: Iteration: 1160 / 1200 [ 96%]  (Sampling)\nChain 3: Iteration: 1200 / 1200 [100%]  (Sampling)\nChain 3: \nChain 3:  Elapsed Time: 0.003 seconds (Warm-up)\nChain 3:                0.038 seconds (Sampling)\nChain 3:                0.041 seconds (Total)\nChain 3: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 4).\nChain 4: \nChain 4: Gradient evaluation took 1.5e-05 seconds\nChain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.15 seconds.\nChain 4: Adjust your expectations accordingly!\nChain 4: \nChain 4: \nChain 4: Iteration:    1 / 1200 [  0%]  (Warmup)\nChain 4: Iteration:  120 / 1200 [ 10%]  (Warmup)\nChain 4: Iteration:  201 / 1200 [ 16%]  (Sampling)\nChain 4: Iteration:  320 / 1200 [ 26%]  (Sampling)\nChain 4: Iteration:  440 / 1200 [ 36%]  (Sampling)\nChain 4: Iteration:  560 / 1200 [ 46%]  (Sampling)\nChain 4: Iteration:  680 / 1200 [ 56%]  (Sampling)\nChain 4: Iteration:  800 / 1200 [ 66%]  (Sampling)\nChain 4: Iteration:  920 / 1200 [ 76%]  (Sampling)\nChain 4: Iteration: 1040 / 1200 [ 86%]  (Sampling)\nChain 4: Iteration: 1160 / 1200 [ 96%]  (Sampling)\nChain 4: Iteration: 1200 / 1200 [100%]  (Sampling)\nChain 4: \nChain 4:  Elapsed Time: 0.006 seconds (Warm-up)\nChain 4:                0.06 seconds (Sampling)\nChain 4:                0.066 seconds (Total)\nChain 4: \n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-34-1.svg){fig-align='center' width=1152}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nbad_example <- stan_glm(\n  hwy ~ cyl,\n  data = filtered_mpg,\n  seed = 12345,\n  chains = 4,\n  iter = 1200,\n  warmup = 200,\n  adapt_delta = 0.7,\n  control = list(\n    max_treedepth = 2\n  )\n)\nmcmc_trace(bad_example) +\n  scale_color_manual(values = scale_colors)\n```\n:::\n\n:::\n:::\n\n<!-- ::: {.column width=\"45%\"} -->\n<!-- ::: {.panel-tabset} -->\n<!-- ### Plot -->\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-height: 3 -->\n<!-- #| fig-width: 12 -->\n<!-- #| fig-align: center -->\n<!-- mcmc_rank_overlay(bad_example) + -->\n<!--   scale_color_manual(values = scale_colors) -->\n<!-- ``` -->\n\n<!-- ### Code -->\n<!-- ```{r} -->\n<!-- #| eval: false -->\n<!-- mcmc_rank_overlay(bad_example) + -->\n<!--   scale_color_manual(values = scale_colors) -->\n<!-- ``` -->\n<!-- ::: -->\n<!-- ::: -->\n\n::: {.column width=\"10%\"}\n[Ick!]{.fragment}\n:::\n::::\n\n\n## Rhat\n\nLooking at traceplots is great, but it's also helpful to have a numerical measure of how well the chains mixed. Especially when you have lots of parameters, not just three.\n\n[Rhat ($\\hat{R}$, read \"R-hat\") is a measure of convergence among different MCMC *chains*.]{.fragment}\n\n[The main idea of $\\hat{R}$ is to compare the variance *between* chains to the variance *within* chains.]{.fragment}\n\n\n## Rhat Visualized: Bad\n\nThe main idea of $\\hat{R}$ is to compare the variance *between* chains to the variance *within* chains.\n\n:::: {.columns}\n::: {.column width=\"70%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-36-1.svg){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n\n:::\n::::\n\n\n\n\n## Rhat Visualized: Bad\n\nThe main idea of $\\hat{R}$ is to compare the variance *between* chains to the variance *within* chains.\n\n:::: {.columns}\n::: {.column width=\"70%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-37-1.svg){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n\n:::\n::::\n\n\n\n\n## Rhat Visualized: Bad\n\nThe main idea of $\\hat{R}$ is to compare the variance *between* chains to the variance *within* chains.\n\n:::: {.columns}\n::: {.column width=\"70%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-38-1.svg){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n\n:::\n::::\n\n\n## Rhat Visualized: Bad\n\nThe main idea of $\\hat{R}$ is to compare the variance *between* chains to the variance *within* chains.\n\n:::: {.columns}\n::: {.column width=\"70%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-39-1.svg){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column .fragment width=\"30%\"}\nVariance between chain means is sooo different from variance within chains!\n:::\n::::\n\n\n## Rhat Visualized: Good\n\nThe main idea of $\\hat{R}$ is to compare the variance *between* chains to the variance *within* chains.\n\n:::: {.columns}\n::: {.column width=\"70%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-40-1.svg){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n\n:::\n::::\n\n\n\n\n## Rhat Visualized: Good\n\nThe main idea of $\\hat{R}$ is to compare the variance *between* chains to the variance *within* chains.\n\n:::: {.columns}\n::: {.column width=\"70%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-41-1.svg){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n\n:::\n::::\n\n\n## Rhat Visualized: Good\n\nThe main idea of $\\hat{R}$ is to compare the variance *between* chains to the variance *within* chains.\n\n:::: {.columns}\n::: {.column width=\"70%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-42-1.svg){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n::: {.column .fragment width=\"30%\"}\nVariance between chain means is very close to variance within chains!\n\n:::\n::::\n\n\n\n## Rhat\n\nIn practice, you want to see $\\hat{R}$ values less than 1.01.\n\n:::: {.columns}\n::: {.column width=\"40%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bayes_t_test_v2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       gaussian [identity]\n formula:      hwy ~ cyl\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 151\n predictors:   2\n\nEstimates:\n              mean   sd    10%   50%   90%\n(Intercept)  28.8    0.5  28.2  28.8  29.4\ncyl8        -11.2    0.7 -12.0 -11.2 -10.3\nsigma         4.0    0.2   3.7   4.0   4.3\n\nFit Diagnostics:\n           mean   sd   10%   50%   90%\nmean_PPD 23.6    0.5 23.0  23.6  24.2 \n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n              mcse Rhat n_eff\n(Intercept)   0.0  1.0  3469 \ncyl8          0.0  1.0  3757 \nsigma         0.0  1.0  3676 \nmean_PPD      0.0  1.0  3932 \nlog-posterior 0.0  1.0  1879 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"60%\"}\n::: fragment\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bayes_t_test_v2)[, \"Rhat\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)          cyl8         sigma      mean_PPD log-posterior \n    0.9998975     0.9994758     0.9995274     1.0007799     0.9999540 \n```\n\n\n:::\n:::\n\n:::\n:::\n::::\n\n\n## Effective Sample Size (ESS)\n\nIn order to closely approximate the posterior ($P(\\theta | D)$, the point of this all!), we need to make sure we have a large number of MCMC samples.\n\nBut one issue: the samples within a chain are **not** independent samples.\n\n:::: {.columns}\n::: {.column width=\"33%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-45-1.svg){fig-align='center' width=576}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- bayesplot::example_mcmc_draws(chains = 1, params = 1)\nbayesplot::mcmc_trace(x) +\n  scale_color_manual(values = scale_colors)\n```\n:::\n\n:::\n\n\n:::\n\n::: {.column width=\"66%\"}\nDo you see how they follow each other around?\n\nESS accounts for that *autocorrelation*. No hard and fast rule, but might be concerned if ESS is lower than 400 or lower than 10% of your total samples.\n:::\n::::\n\n\n## Effective Sample Size (ESS)\n\nLet's check our ESS values.\n\n:::: {.columns}\n::: {.column width=\"40%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bayes_t_test_v2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       gaussian [identity]\n formula:      hwy ~ cyl\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 151\n predictors:   2\n\nEstimates:\n              mean   sd    10%   50%   90%\n(Intercept)  28.8    0.5  28.2  28.8  29.4\ncyl8        -11.2    0.7 -12.0 -11.2 -10.3\nsigma         4.0    0.2   3.7   4.0   4.3\n\nFit Diagnostics:\n           mean   sd   10%   50%   90%\nmean_PPD 23.6    0.5 23.0  23.6  24.2 \n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n              mcse Rhat n_eff\n(Intercept)   0.0  1.0  3469 \ncyl8          0.0  1.0  3757 \nsigma         0.0  1.0  3676 \nmean_PPD      0.0  1.0  3932 \nlog-posterior 0.0  1.0  1879 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"60%\"}\n::: fragment\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bayes_t_test_v2)[, \"n_eff\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)          cyl8         sigma      mean_PPD log-posterior \n         3469          3757          3676          3932          1879 \n```\n\n\n:::\n:::\n\n:::\n:::\n::::\n\n\n<!-- ## Effective Sample Size (ESS) -->\n\n<!-- Bulk and Tail ESS tell you about your effective sample size in the center (bulk) of the distribution and the tails of the distribution.  -->\n\n<!-- :::: {.columns} -->\n<!-- ::: {.column width=\"50%\"} -->\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-width: 5 -->\n<!-- #| fig-height: 3 -->\n<!-- post_col  <- \"#8C7AAE\" -->\n<!-- annot_col <- scales::col_darker(post_col, 30) -->\n\n<!-- # Posterior quantiles for placing the annotations -->\n<!-- tail_x <- qbeta(0.99, a + k, b + n - k) -->\n<!-- tail_y <- dbeta(tail_x, a + k, b + n - k) -->\n\n<!-- base_plot <- just_prior_and_likelihood |> -->\n<!--   ggplot(aes(x, y, label = curve, linetype = curve)) + -->\n<!--   geomtextpath::geom_textline( -->\n<!--     aes(color = curve), -->\n<!--     linewidth = 1, -->\n<!--     hjust = just_prior_and_likelihood$hjust, -->\n<!--     vjust = -0.2, -->\n<!--     size = 5 -->\n<!--   ) + -->\n<!--   # Bulk annotation -->\n<!--   annotate(\"curve\", -->\n<!--            x = post_mode - 0.15, xend = post_mode - 0.1, -->\n<!--            y = post_peak * 0.76, yend = post_peak * 0.68, -->\n<!--            curvature = -0.25, -->\n<!--            arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"), -->\n<!--            linewidth = 0.6, color = annot_col) + -->\n<!--   annotate(\"text\", -->\n<!--            x = post_mode - 0.34, y = post_peak * 0.75, -->\n<!--            label = str_wrap(\"Do I have enough samples of the posterior here?\", 22), -->\n<!--            hjust = 0, vjust = 0, size = 4.5, lineheight = 0.9, -->\n<!--            color = annot_col) + -->\n<!--   # Tail annotation -->\n<!--   annotate(\"curve\", -->\n<!--            x = tail_x + 0.12, xend = tail_x + 0.005, -->\n<!--            y = 1.5, yend = tail_y + 0.05, -->\n<!--            curvature = 0.25, -->\n<!--            arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"), -->\n<!--            linewidth = 0.6, color = annot_col) + -->\n<!--   annotate(\"text\", -->\n<!--            x = tail_x + 0.13, y = 1.55, -->\n<!--            label = \"How about here?\", -->\n<!--            hjust = 0, vjust = 0, size = 4.5, lineheight = 0.9, -->\n<!--            color = annot_col) + -->\n<!--   scale_linetype_manual(values = c(Prior = \"dotted\", Likelihood = \"dashed\", Posterior = \"solid\")) + -->\n<!--   scale_color_manual(values = c(Prior = \"steelblue\", Likelihood = \"#D98282\", Posterior = \"#8C7AAE\")) + -->\n<!--   coord_cartesian(xlim = c(0, 1), ylim = c(0, 4.1), clip = \"off\") + -->\n<!--   theme_void() + -->\n<!--   theme(legend.position = \"none\") -->\n\n<!-- base_plot + -->\n<!--   geom_density( -->\n<!--     data = posterior_samples, -->\n<!--     aes(x = x), -->\n<!--     inherit.aes = FALSE, -->\n<!--     fill = post_col, color = post_col, alpha = 0.3, linewidth = 1 -->\n<!--   ) + -->\n<!--   geom_segment( -->\n<!--     data = posterior_samples, -->\n<!--     aes(x = x, xend = x, y = 0, yend = 0.2), -->\n<!--     inherit.aes = FALSE, -->\n<!--     color = scales::col_darker(post_col, 30), linewidth = 0.7, alpha = 0.35 -->\n<!--   ) + -->\n<!--   guides(color = guide_none(), alpha = guide_none()) + -->\n<!--   theme_void() + -->\n<!--   theme(plot.title = element_text(size = 14, color = \"grey40\", hjust = 0.02), -->\n<!--         legend.position = \"none\") -->\n<!-- ``` -->\n<!-- ::: -->\n\n<!-- ::: {.column width=\"50%\"} -->\n<!-- ```{r} -->\n<!-- # install.packages(\"posterior\") -->\n<!-- posterior::summarise_draws(bayes_t_test_v2,  -->\n<!--                            \"mean\", \"sd\",  -->\n<!--                            \"ess_bulk\", \"ess_tail\") -->\n<!-- ``` -->\n<!-- ::: -->\n<!-- :::: -->\n\n\n## Warnings\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbad_example <- stan_glm(hwy ~ cyl, data = filtered_mpg, seed = 12345, iter = 40)\n```\n:::\n\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_07_files/figure-revealjs/unnamed-chunk-50-1.svg){fig-align='center' width=576}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nbad_example <- stan_glm(hwy ~ cyl, data = filtered_mpg, seed = 12345, iter = 40, refresh = 0)\n\nmcmc_trace(bad_example) +\n  scale_color_manual(values = scale_colors)\n```\n:::\n\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n**Output**\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 1).\nChain 1: \nChain 1: Gradient evaluation took 2.1e-05 seconds\nChain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.21 seconds.\nChain 1: Adjust your expectations accordingly!\nChain 1: \nChain 1: \nChain 1: WARNING: There aren't enough warmup iterations to fit the\nChain 1:          three stages of adaptation as currently configured.\nChain 1:          Reducing each adaptation stage to 15%/75%/10% of\nChain 1:          the given number of warmup iterations:\nChain 1:            init_buffer = 3\nChain 1:            adapt_window = 15\nChain 1:            term_buffer = 2\nChain 1: \nChain 1: Iteration:  1 / 40 [  2%]  (Warmup)\nChain 1: Iteration:  4 / 40 [ 10%]  (Warmup)\nChain 1: Iteration:  8 / 40 [ 20%]  (Warmup)\nChain 1: Iteration: 12 / 40 [ 30%]  (Warmup)\nChain 1: Iteration: 16 / 40 [ 40%]  (Warmup)\nChain 1: Iteration: 20 / 40 [ 50%]  (Warmup)\nChain 1: Iteration: 21 / 40 [ 52%]  (Sampling)\nChain 1: Iteration: 24 / 40 [ 60%]  (Sampling)\nChain 1: Iteration: 28 / 40 [ 70%]  (Sampling)\nChain 1: Iteration: 32 / 40 [ 80%]  (Sampling)\nChain 1: Iteration: 36 / 40 [ 90%]  (Sampling)\nChain 1: Iteration: 40 / 40 [100%]  (Sampling)\nChain 1: \nChain 1:  Elapsed Time: 0.001 seconds (Warm-up)\nChain 1:                0.006 seconds (Sampling)\nChain 1:                0.007 seconds (Total)\nChain 1: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 2).\nChain 2: \nChain 2: Gradient evaluation took 1.1e-05 seconds\nChain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.11 seconds.\nChain 2: Adjust your expectations accordingly!\nChain 2: \nChain 2: \nChain 2: WARNING: There aren't enough warmup iterations to fit the\nChain 2:          three stages of adaptation as currently configured.\nChain 2:          Reducing each adaptation stage to 15%/75%/10% of\nChain 2:          the given number of warmup iterations:\nChain 2:            init_buffer = 3\nChain 2:            adapt_window = 15\nChain 2:            term_buffer = 2\nChain 2: \nChain 2: Iteration:  1 / 40 [  2%]  (Warmup)\nChain 2: Iteration:  4 / 40 [ 10%]  (Warmup)\nChain 2: Iteration:  8 / 40 [ 20%]  (Warmup)\nChain 2: Iteration: 12 / 40 [ 30%]  (Warmup)\nChain 2: Iteration: 16 / 40 [ 40%]  (Warmup)\nChain 2: Iteration: 20 / 40 [ 50%]  (Warmup)\nChain 2: Iteration: 21 / 40 [ 52%]  (Sampling)\nChain 2: Iteration: 24 / 40 [ 60%]  (Sampling)\nChain 2: Iteration: 28 / 40 [ 70%]  (Sampling)\nChain 2: Iteration: 32 / 40 [ 80%]  (Sampling)\nChain 2: Iteration: 36 / 40 [ 90%]  (Sampling)\nChain 2: Iteration: 40 / 40 [100%]  (Sampling)\nChain 2: \nChain 2:  Elapsed Time: 0.001 seconds (Warm-up)\nChain 2:                0.001 seconds (Sampling)\nChain 2:                0.002 seconds (Total)\nChain 2: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 3).\nChain 3: \nChain 3: Gradient evaluation took 1e-05 seconds\nChain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.1 seconds.\nChain 3: Adjust your expectations accordingly!\nChain 3: \nChain 3: \nChain 3: WARNING: There aren't enough warmup iterations to fit the\nChain 3:          three stages of adaptation as currently configured.\nChain 3:          Reducing each adaptation stage to 15%/75%/10% of\nChain 3:          the given number of warmup iterations:\nChain 3:            init_buffer = 3\nChain 3:            adapt_window = 15\nChain 3:            term_buffer = 2\nChain 3: \nChain 3: Iteration:  1 / 40 [  2%]  (Warmup)\nChain 3: Iteration:  4 / 40 [ 10%]  (Warmup)\nChain 3: Iteration:  8 / 40 [ 20%]  (Warmup)\nChain 3: Iteration: 12 / 40 [ 30%]  (Warmup)\nChain 3: Iteration: 16 / 40 [ 40%]  (Warmup)\nChain 3: Iteration: 20 / 40 [ 50%]  (Warmup)\nChain 3: Iteration: 21 / 40 [ 52%]  (Sampling)\nChain 3: Iteration: 24 / 40 [ 60%]  (Sampling)\nChain 3: Iteration: 28 / 40 [ 70%]  (Sampling)\nChain 3: Iteration: 32 / 40 [ 80%]  (Sampling)\nChain 3: Iteration: 36 / 40 [ 90%]  (Sampling)\nChain 3: Iteration: 40 / 40 [100%]  (Sampling)\nChain 3: \nChain 3:  Elapsed Time: 0 seconds (Warm-up)\nChain 3:                0.007 seconds (Sampling)\nChain 3:                0.007 seconds (Total)\nChain 3: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 4).\nChain 4: \nChain 4: Gradient evaluation took 1.6e-05 seconds\nChain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.16 seconds.\nChain 4: Adjust your expectations accordingly!\nChain 4: \nChain 4: \nChain 4: WARNING: There aren't enough warmup iterations to fit the\nChain 4:          three stages of adaptation as currently configured.\nChain 4:          Reducing each adaptation stage to 15%/75%/10% of\nChain 4:          the given number of warmup iterations:\nChain 4:            init_buffer = 3\nChain 4:            adapt_window = 15\nChain 4:            term_buffer = 2\nChain 4: \nChain 4: Iteration:  1 / 40 [  2%]  (Warmup)\nChain 4: Iteration:  4 / 40 [ 10%]  (Warmup)\nChain 4: Iteration:  8 / 40 [ 20%]  (Warmup)\nChain 4: Iteration: 12 / 40 [ 30%]  (Warmup)\nChain 4: Iteration: 16 / 40 [ 40%]  (Warmup)\nChain 4: Iteration: 20 / 40 [ 50%]  (Warmup)\nChain 4: Iteration: 21 / 40 [ 52%]  (Sampling)\nChain 4: Iteration: 24 / 40 [ 60%]  (Sampling)\nChain 4: Iteration: 28 / 40 [ 70%]  (Sampling)\nChain 4: Iteration: 32 / 40 [ 80%]  (Sampling)\nChain 4: Iteration: 36 / 40 [ 90%]  (Sampling)\nChain 4: Iteration: 40 / 40 [100%]  (Sampling)\nChain 4: \nChain 4:  Elapsed Time: 0.001 seconds (Warm-up)\nChain 4:                0.006 seconds (Sampling)\nChain 4:                0.007 seconds (Total)\nChain 4: \n```\n\n\n:::\n:::\n\n:::\n::::\n\n\n## Warnings\n\n[Stan documentation on warnings](https://mc-stan.org/learn-stan/diagnostics-warnings.html)\n\n[`{rstanarm}` documentation on troubleshooting`](https://mc-stan.org/rstanarm/articles/rstanarm.html#troubleshooting){preview-link=\"}\n\nThings to try...\n\n:::: {.columns style=\"font-size:80%\"}\n::: {.column width=\"33%\"}\n**Rhat or ESS too low?**\n\nTry increasing the number of samples (`iter`, default is 1000 for each of four chains).\n:::\n\n::: {.column width=\"33%\"}\n**Divergent transitions?**\n\nIncrease `adapt_delta` towards 1 (default is `0.95`)\n:::\n\n::: {.column width=\"33%\"}\n**Max treedepth exceeded?**\n\nIf everything else is good, probably fine. Otherwise, try increasing `max_treedepth` (default is 15). Add to `control` argument (`control = list(max_treedepth = 16)`).\n:::\n::::\n\n\n## Diagnostics TLDR\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Rhat**\n\nWant $\\hat{R} < 1.01$ for all parameters.\n\n<br>\n:::\n\n::: {.column width=\"50%\"}\n**ESS**\n\nWant ESS > 400ish for all parameters.\n\n<br>\n:::\n::::\n\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Trace Plots**\n\nWant trace plots to look like \"fuzzy caterpillars\" for all parameters. All overlapping, none of the chains higher or lower on average than others.\n:::\n\n::: {.column width=\"50%\"}\n**Warnings**\n\nTry to adjust the sampler if you encounter any warnings. Check for bugs in your formula syntax, increase `iter`, etc. If you can't get the warning to go away, make sure to mention it in your writeup.\n:::\n::::\n\n\n## Bayes Factors\n\nComparing models to each other. Here, an intercept-only model to a slope-and-intercept model.\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"bayestestR\")\n# install.packages(\"bridgesampling\")\nlibrary(bayestestR)\nbayes_t_test_v0 <- stan_glm(\n  hwy ~ 1, data = filtered_mpg,\n  prior_intercept = normal(24, 15),\n  family = \"gaussian\",\n  diagnostic_file = here::here(\"lab\", \"model-diagnostics\",\n                               \"bayes_t_test_v0.csv\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 1).\nChain 1: \nChain 1: Gradient evaluation took 1.9e-05 seconds\nChain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.19 seconds.\nChain 1: Adjust your expectations accordingly!\nChain 1: \nChain 1: \nChain 1: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 1: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 1: \nChain 1:  Elapsed Time: 0.029 seconds (Warm-up)\nChain 1:                0.088 seconds (Sampling)\nChain 1:                0.117 seconds (Total)\nChain 1: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 2).\nChain 2: \nChain 2: Gradient evaluation took 1.5e-05 seconds\nChain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.15 seconds.\nChain 2: Adjust your expectations accordingly!\nChain 2: \nChain 2: \nChain 2: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 2: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 2: \nChain 2:  Elapsed Time: 0.037 seconds (Warm-up)\nChain 2:                0.08 seconds (Sampling)\nChain 2:                0.117 seconds (Total)\nChain 2: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 3).\nChain 3: \nChain 3: Gradient evaluation took 1.3e-05 seconds\nChain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.13 seconds.\nChain 3: Adjust your expectations accordingly!\nChain 3: \nChain 3: \nChain 3: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 3: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 3: \nChain 3:  Elapsed Time: 0.044 seconds (Warm-up)\nChain 3:                0.09 seconds (Sampling)\nChain 3:                0.134 seconds (Total)\nChain 3: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 4).\nChain 4: \nChain 4: Gradient evaluation took 1.1e-05 seconds\nChain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.11 seconds.\nChain 4: Adjust your expectations accordingly!\nChain 4: \nChain 4: \nChain 4: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 4: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 4: \nChain 4:  Elapsed Time: 0.041 seconds (Warm-up)\nChain 4:                0.096 seconds (Sampling)\nChain 4:                0.137 seconds (Total)\nChain 4: \n```\n\n\n:::\n\n```{.r .cell-code}\nbayes_t_test_v2 <- stan_glm(\n  hwy ~ cyl, data = filtered_mpg,\n  prior = normal(0, 1.5, autoscale = T),\n  prior_intercept = normal(24, 15),\n  family = \"gaussian\",\n  diagnostic_file = here::here(\"lab\", \"model-diagnostics\",\n                               \"bayes_t_test_v2.csv\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 1).\nChain 1: \nChain 1: Gradient evaluation took 2.1e-05 seconds\nChain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.21 seconds.\nChain 1: Adjust your expectations accordingly!\nChain 1: \nChain 1: \nChain 1: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 1: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 1: \nChain 1:  Elapsed Time: 0.058 seconds (Warm-up)\nChain 1:                0.115 seconds (Sampling)\nChain 1:                0.173 seconds (Total)\nChain 1: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 2).\nChain 2: \nChain 2: Gradient evaluation took 1.6e-05 seconds\nChain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.16 seconds.\nChain 2: Adjust your expectations accordingly!\nChain 2: \nChain 2: \nChain 2: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 2: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 2: \nChain 2:  Elapsed Time: 0.057 seconds (Warm-up)\nChain 2:                0.082 seconds (Sampling)\nChain 2:                0.139 seconds (Total)\nChain 2: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 3).\nChain 3: \nChain 3: Gradient evaluation took 2.1e-05 seconds\nChain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.21 seconds.\nChain 3: Adjust your expectations accordingly!\nChain 3: \nChain 3: \nChain 3: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 3: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 3: \nChain 3:  Elapsed Time: 0.055 seconds (Warm-up)\nChain 3:                0.112 seconds (Sampling)\nChain 3:                0.167 seconds (Total)\nChain 3: \n\nSAMPLING FOR MODEL 'continuous' NOW (CHAIN 4).\nChain 4: \nChain 4: Gradient evaluation took 1.5e-05 seconds\nChain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.15 seconds.\nChain 4: Adjust your expectations accordingly!\nChain 4: \nChain 4: \nChain 4: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 4: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 4: \nChain 4:  Elapsed Time: 0.059 seconds (Warm-up)\nChain 4:                0.107 seconds (Sampling)\nChain 4:                0.166 seconds (Total)\nChain 4: \n```\n\n\n:::\n\n```{.r .cell-code}\nbayes_factor <- bayesfactor_models(bayes_t_test_v0,\n                                   bayes_t_test_v2)\n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_factor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBayes Factors for Model Comparison\n\n    Model       BF\n[2] cyl   9.45e+33\n\n* Against Denominator: [1] (Intercept only)\n*   Bayes Factor Type: marginal likelihoods (bridgesampling)\n```\n\n\n:::\n:::\n\n\nWe can say the model with the slope term is $9.44\\times10^{33}$ (very large!) times as likely as the model without.\n\n:::\n::::\n\n\n## Lab 07 Assignment\n\nDue **Friday**, 10/16!\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}