{
  "hash": "25640882bb86d91da5d882bcd7d42516",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"*T*-Tests\"\nsubtitle: \"PSYC 6019-A01 / PSYC 6022-A01 <br> 2025-09-25 | Lab 5\"\nauthor: \"Jess Helmer\"\nfooter: \"[jhelmer3.github.io/PSYC6019-2026](https://jhelmer3.github.io/PSYC6019-2026/)\"\nformat: \n  revealjs:\n    code-link: true\n    slide-number: true\n    code-line-numbers: false\n    theme: ../../gt-theme.scss\n    width: 1200\nexecute: \n  echo: true\n  dpi: 600\n  freeze: auto\n---\n\n## Outline\n\n- One sample *t*-test\n\n- Independent samples *t*-test\n\n- Paired samples *t*-test\n\n\n::: {.cell}\n\n:::\n\n\n\n\n# From *Z* to *T*: No longer normal\n\n\n## *Z*- vs. *T*-Distribution\n\n*T*-distribution has thicker tails\n\nAs df increases, it looks more like a standard normal distribution\n\nWith df = $\\infty$, exactly follows a normal distribution (so approximates with large df)\n\n\n## *Z*- vs. *T*-Distribution\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## *Z*- vs. *T*-Distribution\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## *Z*- vs. *T*-Distribution\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## *Z*- vs. *T*-Distribution\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## *Z*- vs. *T*-Distribution\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n## *T*-Test: How many tails?\n\nNeed to consider whether to use a \"one-tail\" or \"two-tail\" *t*-test.\n\n:::: columns\n::: {.column}\n#### One-Tail (One-Sided)\n\nWe want to test whether something is lower or higher than a value, but **not both**\n\nOnly one limit\n:::\n\n::: {.column}\n#### Two-Tails (Two-Sided)\n\nWe want to test whether something is either lower or higher than a value\n\nTwo limits\n:::\n::::\n\n\n## Testing: How many tails?\n\nNeed to consider whether to use a \"one-tail\" or \"two-tail\" *t*-test.\n\n:::: columns\n::: {.column}\n#### One-Tail (One-Sided)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=336}\n:::\n:::\n\n:::\n\n::: {.column}\n#### Two-Tails (Two-Sided)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=336}\n:::\n:::\n\n:::\n::::\n\n\n## Testing: How many tails?\n\nNotice that two-tailed tests are harder to \"beat.\"\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=816}\n:::\n:::\n\n\n\n## Types of *T*-Tests\n\n![](https://media.geeksforgeeks.org/wp-content/uploads/20250128171318605791/Types-of-t-test.webp)\n\n\n\n# One-Sample *T*-Test\n\n\n## One-Sample *T*-Test Generally\n\nAsks \"is there a question between our sample and the population?\"\n\nDerived with sample mean ($\\bar{x}$), population mean ($\\mu$), and standard error ($SE = \\frac{s}{\\sqrt n}$)\n\n$$t = \\frac{\\bar{x} - \\mu}{SE} = \\frac{\\bar{x} - \\mu}{\\frac{s}{\\sqrt{n}}}$$\n\nWith a *t*-test, we don't have a known population SD ($\\sigma$), so we use the SD we observe in our sample $s$.\n\n:::: {.columns}\n::: {.column .fragment width=\"50%\"}\nOften, we compare our sample mean to a hypothesized mean of zero\n\n$H_0$: $\\mu = 0$\n\n$H_1$: $\\mu \\neq 0$\n:::\n\n::: {.column .fragment width=\"50%\"}\nIf that's the case, our *t*-statistic calculation reduces to \n\n$t \\bigg|_{\\mu = 0} = \\frac{\\bar{x} - 0}{\\frac{s}{\\sqrt{n}}} = \\frac{\\bar{x}}{\\frac{s}{\\sqrt{n}}}$\n:::\n::::\n\n\n## *T*-Test Example\n\nLet's say a researcher claims the average city miles per gallon across all cars is 30mpg. They collect a sample of 234 cars and would like you to test this. We do not know the population standard deviation.\n\n::: fragment\nOne- or two-tailed?\n:::\n\n:::: {.columns style=\"font-size:80%\"}\n::: {.column .fragment width=\"75%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mpg$cty)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18 21 20 21 16 18\n```\n\n\n:::\n\n```{.r .cell-code}\nx_bar <- mean(mpg$cty)\nx_sd <- sd(mpg$cty)\nn <- length(mpg$cty) # this won't work if you have missing data\ndf <- n - 1\n\nt_cutoff <- qt(.975, df)\n\nx_se <- x_sd / sqrt(n)\n\ncty_t_stat <- (x_bar - 30) / x_se\ncty_t_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -47.23252\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"25%\"}\n[Our observed *t*-statistic exceeds our cutoff *t*-statistic, so we reject the null.]{.fragment}\n:::\n::::\n\n\n## *T*-Test Function\n\nAlternatively, we can use `t.test(x)`\n\n<div class=\"subpoint\">○ `x` = vector of numeric data </div>\n\n<div class=\"subpoint\">○ `mu` = hypothesized population mean (default is 0) </div>\n\n<div class=\"subpoint\">○ `alternative` = one of `\"two.sided\"`, `\"less\"`, `\"greater\"` (default is `\"two.sided\"`) </div>\n\n:::: {.columns style=\"font-size:80%\"}\n::: {.column .fragment width=\"75%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nt.test(mpg$cty, mu = 30, alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  mpg$cty\nt = -47.233, df = 233, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 30\n95 percent confidence interval:\n 16.31083 17.40712\nsample estimates:\nmean of x \n 16.85897 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"25%\"}\n[We see a significant difference between our observed sample mean and our hypothesized population mean.]{.fragment}\n:::\n::::\n\n\n## *T*-Test Assumptions\n\n::: {style=\"font-size:80%\"}\nWe can create QQ plots with `ggplot`\n\n`geom_qq()` adds the points, `geom_qq_line()` adds the expected line.\n\nThe `aes()` we need to specify is `sample`\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |>\n  ggplot(aes(x = cty)) +\n  geom_histogram(aes(y = after_stat(density)), binwidth = 3) +\n  geom_density() \n```\n:::\n\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |>\n  ggplot(aes(sample = cty)) +\n  geom_qq() +\n  geom_qq_line()\n```\n:::\n\n:::\n\n:::\n::::\n\n:::\n\n\n## *T*-Test Example Output\n\n:::: {.columns}\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\ncty_ttest <- t.test(mpg$cty)\ncty_ttest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  mpg$cty\nt = 60.596, df = 233, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 16.31083 17.40712\nsample estimates:\nmean of x \n 16.85897 \n```\n\n\n:::\n\n```{.r .cell-code}\n#?t.test\n```\n:::\n\n:::\n\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\ncty_ttest$statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       t \n60.59587 \n```\n\n\n:::\n\n```{.r .cell-code}\ncty_ttest$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.276375e-144\n```\n\n\n:::\n:::\n\n\n::: fragment\n\n::: {.cell}\n\n```{.r .cell-code}\ncty_ttest$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16.31083 17.40712\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n:::\n::::\n\n\n## *T*-Test Confidence Intervals\n\nLet's build a confidence interval around our estimated mean\n\n$$ CI = [\\bar{x} - t_{crit} \\times s_{\\bar{x}}, \\ \\bar{x} + t_{crit} \\times s_{\\bar{x}}] $$\n<div class=\"subpoint\">○ $\\bar{x}$ = our observed mean </div>\n\n<div class=\"subpoint\">○ $t_{crit}$ = our critical *t* value </div>\n\n<div class=\"subpoint\">○ $s_{\\bar{x}}$ = the standard error of our outcome </div>\n\n\n## *T*-Test Confidence Intervals\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mpg$cty)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18 21 20 21 16 18\n```\n\n\n:::\n\n```{.r .cell-code}\nx_bar <- mean(mpg$cty)\nx_sd <- sd(mpg$cty)\nn <- length(mpg$cty)\ndf <- n - 1\n\nt_cutoff <- qt(.975, df)\n\nx_se <- x_sd / sqrt(n)\n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nci_lower <- x_bar - t_cutoff * x_se\nci_upper <- x_bar + t_cutoff * x_se\nc(ci_lower, ci_upper)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16.31083 17.40712\n```\n\n\n:::\n:::\n\n:::\n::::\n\n[Across repeated trials, 95% of intervals (across repeated samples) will contain the true value. [16.31, 17.41] is one such interval.]{.fragment}\n\n[If we treated any value inside the 95% confidence interval of [16.31, 17.41] as the null, we could not reject it at $\\alpha = 0.05$.]{.fragment}\n\n\n\n## *T*-Test Example\n\nLet's say a different researcher claims the average city miles per gallon across all cars is 30mpg. They collect a sample of 234 cars You are confident they are wrong---you think it is certainly less than that. We do not know the population standard deviation.\n\n::: fragment\nOne- or two-tailed?\n:::\n\n:::: {.columns style=\"font-size:80%\"}\n::: {.column .fragment width=\"75%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(mpg$cty, mu = 30, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  mpg$cty\nt = -47.233, df = 233, p-value < 2.2e-16\nalternative hypothesis: true mean is less than 30\n95 percent confidence interval:\n     -Inf 17.31843\nsample estimates:\nmean of x \n 16.85897 \n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"25%\"}\n[We see a significant difference between our observed sample mean and our hypothesized population mean.]{.fragment}\n:::\n::::\n\n\n## *T*-Statistic Cutoffs\n\nSay you want to find the cutoff *t* values: $t(\\text{df}=3)$ and $t(\\text{df}=37)$ for $\\alpha = .05$, both upper one-tailed and two-tailed.\n\n::: fragment\nWhich will have the larger magnitude cutoff values?\n:::\n\n:::: {.columns .fragment style=\"font-size:70%\"}\n::: column\n**One-Tailed**\n\nAll of our $\\alpha = .05$ goes on the upper side\n\nNeed a cutoff for $.95$\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(p = .95, df = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.353363\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(p = .05, df = 37, lower.tail = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.687094\n```\n\n\n:::\n:::\n\n\n$t_{crit}(\\text{df}=3) = 2.35$\n\n$t_{crit}(\\text{df}=37) = 1.69$\n:::\n\n::: column\n**Two-Tailed**\n\n$\\alpha = 1 - .95 = 5\\%$ on both sides\n\nSo $.05 / 2 = .025$ on each side\n\nNeed value for $.025$ and $.95 + .025$ ($[.025, .975]$)\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(p = c(.025, .975), df = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -3.182446  3.182446\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(p = c(.025, .975), df = 37)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2.026192  2.026192\n```\n\n\n:::\n:::\n\n\n$t_{crit}(\\text{df}=3) = [-3.18, 3.18]$\n\n$t_{crit}(\\text{df}=37) = [-2.03, 2.03]$\n:::\n::::\n\n\n\n# Independent Samples *T*-Test\n\n## Independent Samples *T*-Test\n\nMight want to compare two samples of observations\n\n[○ Post-graduation salaries of GT vs. UGA grads]{.subpoint}\n\n[○ Treatment vs. control group]{.subpoint}\n\n[○ Cats vs. dogs]{.subpoint}\n\nWe can represent each group with their mean on some outcome and compare the means\n\nConsider whether the mean difference is significant but also have to account for different levels of variability within group\n\n\n## Independent Samples *T*-Test: Test Statistic\n\n$$ t = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{\\frac{s_p^2}{n_1} + \\frac{s_p^2}{n_2}}} = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_p\\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}} $$\n\n[Compare against critical *t*-value with df = $(n_1 - 1) + (n_2 - 1)$]{.fragment}\n\n\n## Independent Samples *T*-Test: Pooled SD\n\nNeed to pool the sample SDs while noting different sample sizes\n\n$$ s_p^2 = \\frac{(n_1 - 1) s_1^2 + (n_2 - 1) s_2^2}{(n_1 - 1) + (n_2 - 1)} = \\frac{(n_1 - 1) s_1^2 + (n_2 - 1) s_2^2}{n_1 + n_2 - 2}$$\n\n\n## Independent Samples *T*-Test: Pooled SD\n\nNote that when sample size is equal (i.e., $n_1 = n_2 = n$),\n\n::: math\n\\begin{array}{ll}\ns_p^2 \\bigg|_{n_1 = n_2 = n} & = \\frac{(n - 1) s_1^2 + (n - 1) s_2^2}{(n - 1) + (n - 1)} = \\frac{(n - 1) (s_1^2 + s_2^2)}{(n - 1) + (n - 1)} \\\\[0.6em]\n& = \\frac{(n - 1) (s_1^2 + s_2^2)}{2(n - 1)} = \\frac{s_1^2 + s_2^2}{2}\n\\end{array}\n:::\n\n::: fragment\nSquare root to get back to standard deviation\n\n$$ s_p = \\sqrt{s_p^2} = \\sqrt{\\frac{(n_1 - 1) s_1^2 + (n_2 - 1) s_2^2}{(n_1 - 1) + (n_2 - 1)}} = \\sqrt{\\frac{(n_1 - 1) s_1^2 + (n_2 - 1) s_2^2}{n_1 + n_2 - 2}} $$\n:::\n\n\n## Independent Samples *T*-Test: Example\n\nLet's say you work for a car manufacturer, and you're helping decide features of the next car you produce. You want to test whether there's a difference in highway MPG for cars with four and eight cylinders. You have a dataset with 234 cars to test this on.\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_mpg <- mpg |>\n  filter(when_any(cyl == 4, cyl == 8))\n\nfour_cyl <- mpg |>\n  filter(cyl == 4) |>\n  pull(hwy)\n\neight_cyl <- mpg |>\n  filter(cyl == 8) |>\n  pull(hwy)\n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(four_cyl); head(eight_cyl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 29 29 31 30 26 25\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23 20 15 20 17 17\n```\n\n\n:::\n:::\n\n:::\n::::\n\n\n## Independent Samples *T*-Test: R Calculation\n\n$$ t = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{\\frac{s_p^2}{n_1} + \\frac{s_p^2}{n_2}}} = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_p\\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}} $$\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nx_bar_four <- mean(four_cyl)\nsd_four <- sd(four_cyl)\nn_four <- length(four_cyl)\n\nx_bar_eight <- mean(eight_cyl)\nsd_eight <- sd(eight_cyl)\nn_eight <- length(eight_cyl)\n\nx_bar_four; x_bar_eight\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28.80247\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17.62857\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npooled_sd <- sqrt(\n  ((n_four - 1) * sd_four^2 + (n_eight - 1) * sd_eight^2) /\n    ((n_four - 1) + (n_eight - 1)) \n)\npooled_sd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.984182\n```\n\n\n:::\n\n```{.r .cell-code}\nse <- pooled_sd * sqrt(1 / n_four + 1 / n_eight)\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6501838\n```\n\n\n:::\n:::\n\n:::\n::::\n\n\n## Independent Samples *T*-Test: R Calculation\n\n::: fragment\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- (n_four - 1) + (n_eight - 1)\n\nt_crits <- qt(c(.025, .975), df)\nt_crits\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.976013  1.976013\n```\n\n\n:::\n:::\n\n\nIf our observed *t*-statistic exceeds the bounds of [-1.98, 1.98], we reject the null.\n:::\n\n::: fragment\n\n::: {.cell}\n\n```{.r .cell-code}\nt_stat <- (x_bar_four - x_bar_eight) / se\nt_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17.18575\n```\n\n\n:::\n:::\n\n:::\n\n[We reject the null! Can we tell which had a larger mean?]{.fragment}\n\n\n## Independent Samples *T*-Test: CI\n\nLet's build a confidence interval around our estimated difference in means\n\n$$ CI = [\\bar{d} - t_{crit} \\times s_{\\bar{x}}, \\ \\bar{d} + t_{crit} \\times s_{\\bar{x}}] $$\n<div class=\"subpoint\">○ $\\bar{d}$ = our observed mean difference ($\\bar{x}_{\\text{group 1}} - \\bar{x}_{\\text{group 2}}$) </div>\n\n<div class=\"subpoint\">○ $t_{crit}$ = our critical *t* value </div>\n\n<div class=\"subpoint\">○ $s_{\\bar{x}}$ = the standard error of our outcome </div>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_bar_difference <- x_bar_four - x_bar_eight\n\nx_bar_difference + t_crits * se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  9.889126 12.458669\n```\n\n\n:::\n:::\n\n\n\n## Independent Samples *T*-Test: R Function\n\n`t.test(outcome ~ group_var, data, var.equal = T)`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(hwy ~ cyl, filtered_mpg, var.equal = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  hwy by cyl\nt = 17.186, df = 149, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group 4 and group 8 is not equal to 0\n95 percent confidence interval:\n  9.889126 12.458669\nsample estimates:\nmean in group 4 mean in group 8 \n       28.80247        17.62857 \n```\n\n\n:::\n:::\n\n\n\n## Independent Samples *T*-Test Assumptions\n\n::: {style=\"font-size:80%\"}\nDifferentiate groups by specifying the `group` aesthetic\n\nLook for normality and *homogeneity of variance*: both groups have the same variance\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-31-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_mpg |>\n  ggplot(aes(x = hwy, color = cyl, fill = cyl, group = cyl)) +\n  geom_histogram(aes(y = after_stat(density)), binwidth = 3, alpha = 0.4, color = NA) +\n  geom_density(alpha = 0.6) +\n  theme_classic()\n```\n:::\n\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-33-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_mpg |>\n  ggplot(aes(sample = hwy, color = cyl, group = cyl)) +\n  geom_qq() +\n  geom_qq_line() +\n  theme_classic()\n```\n:::\n\n:::\n\n:::\n::::\n\n:::\n\n\n## Homogeneity of Variance\n\nHomogeneity of variance assumption:\n\n::::: {.columns}\n:::: {.column width=\"50%\"}\n**GOOD**\n\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-35-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_size <- 10000\ntibble(x1 = rnorm(sample_size, 12, 3),\n       x2 = rnorm(sample_size, 20, 3)) |>\n  pivot_longer(starts_with(\"x\"), names_to = \"group\", values_to = \"draw\") |>\n  ggplot(aes(x = draw, color = group)) +\n  geom_density() +\n  coord_cartesian(xlim = c(0, 40)) +\n  theme_classic()\n```\n:::\n\n:::\n::::\n\n:::: {.column width=\"50%\"}\n**BAD**\n\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-37-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_size <- 10000\ntibble(x1 = rnorm(sample_size, 12, 2),\n       x2 = rnorm(sample_size, 20, 6)) |>\n  pivot_longer(starts_with(\"x\"), names_to = \"group\", values_to = \"draw\") |>\n  ggplot(aes(x = draw, color = group)) +\n  geom_density() +\n  coord_cartesian(xlim = c(0, 40)) +\n  theme_classic()\n```\n:::\n\n:::\n::::\n:::::\n\n\n\n# Paired Samples *T*-Test\n\n\n## Paired Samples *T*-Test\n\nComparing the same subjects under two conditions (often two timepoints)\n\n[○ Stress levels before vs. after a test]{.subpoint}\n\n[○ Reaction times before vs. after caffiene consumption]{.subpoint}\n\n[○ Anxiety levels before vs. after a mindfulness intervention]{.subpoint}\n\nWe can still use the mean to represent the observations in each condition and make comparisons\n\nThis time, focus on difference scores (individual differences in the observations between the two conditions)\n\n\n## Paired Samples *T*-Test\n\nNeed difference score for each observation $d_i = x_2 - x_1$\n\nThen, get mean difference $\\bar{d} = \\frac{d_1 \\ + \\ d_2 \\ + \\ ... \\ + \\ d_n}{n}$ and standard deviation of those difference scores $s_d = \\sqrt{\\frac{(d_1-\\bar{d})^2 \\ + \\ (d_2-\\bar{d})^2 \\ + \\ ... \\ + \\ (d_n-\\bar{d})^2}{n - 1}}$\n\n$$ t = \\frac{\\bar{d} - \\mu_{d_0}}{\\frac{s_d}{\\sqrt{n}}} = \\text{(usually)} \\frac{\\bar{d} - 0}{\\frac{s_d}{\\sqrt{n}}} = \\frac{\\bar{d}}{\\frac{s_d}{\\sqrt{n}}}$$\n\nCompare against critical *t*-value with df = $n - 1$\n\n\n## Paired Samples *T*-Test: R Example\n\nYou own an ice cream shop, and you want to decide which flavor of ice cream (vanilla or cookie dough) you want to run a promotion for! The promotion would be for the ice cream flavor that has been selling less. For 20 days, you track the sales of each ice cream flavor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nice_cream_sales <- read.csv(here::here(\"lab\", \"data\", \"lab_04\", \"ice_cream_sales_data.csv\"))\n\nglimpse(ice_cream_sales)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 40\nColumns: 3\n$ flavor <chr> \"vanilla\", \"vanilla\", \"vanilla\", \"vanilla\", \"vanilla\", \"vanilla…\n$ sales  <dbl> 49.17, 52.01, 51.47, 48.10, 53.97, 50.30, 55.69, 51.83, 46.02, …\n$ day    <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, …\n```\n\n\n:::\n:::\n\n\n\n## Paired Samples *T*-Test: Difference Scores\n\nFor a paired samples *t*-test, our unit of analysis is a *difference score*. So, currently, this data is too long! Let's pivot and create some difference scores.\n\n::: fragment\n\n::: {.cell}\n\n```{.r .cell-code}\nice_cream_cleaned <- ice_cream_sales |>\n  pivot_wider(names_from = flavor, values_from = sales) |>\n  mutate(difference = vanilla - cookie_dough)\nhead(ice_cream_cleaned)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n    day vanilla cookie_dough difference\n  <int>   <dbl>        <dbl>      <dbl>\n1     1    49.2         46.8       2.41\n2     2    52.0         48.9       3.1 \n3     3    51.5         40.0      11.5 \n4     4    48.1         45.1       2.96\n5     5    54.0         43.0      11.0 \n6     6    50.3         40.5       9.84\n```\n\n\n:::\n:::\n\n:::\n\n\n## Paired Samples *T*-Test: R Calculation\n\n::: fragment\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_mean_diff <- mean(ice_cream_cleaned$difference)\nsd_diff <- sd(ice_cream_cleaned$difference)\nn_diff <- nrow(ice_cream_cleaned)\n\nse_diff <- sd_diff / sqrt(n_diff)\nobs_mean_diff; se_diff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.261\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.919921\n```\n\n\n:::\n:::\n\n:::\n\n\n## Paired Samples *T*-Test: R Calculation\n\n::: fragment\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- (n_diff - 1)\n\nt_crits <- qt(c(.025, .975), df)\nt_crits\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2.093024  2.093024\n```\n\n\n:::\n:::\n\n\nIf our observed *t*-statistic exceeds the bounds of [-2.09, 2.09], we reject the null.\n:::\n\n::: fragment\n\n::: {.cell}\n\n```{.r .cell-code}\nt_stat <- obs_mean_diff / se_diff\nt_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.823637\n```\n\n\n:::\n:::\n\n:::\n\n\n## Paired Samples *T*-Test: R Calculation\n\nLet's build a confidence interval around our estimated difference in means\n\n$$ CI = [\\bar{d} - t_{crit} \\times s_{\\bar{x}}, \\ \\bar{d} + t_{crit} \\times s_{\\bar{x}}] $$\n<div class=\"subpoint\">○ $\\bar{d}$ = our observed mean difference ($\\bar{x}_{\\text{group 1}} - \\bar{x}_{\\text{group 2}}$) </div>\n\n<div class=\"subpoint\">○ $t_{crit}$ = our critical *t* value </div>\n\n<div class=\"subpoint\">○ $s_{\\bar{x}}$ = the standard error of our outcome </div>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci <- obs_mean_diff + t_crits * se_diff\nci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  5.24256 13.27944\n```\n\n\n:::\n:::\n\n\nCI: [5.24, 13.28]\n\n\n## Paired Samples *T*-Test: R Function\n\n`t.test(y1_vector, y2_vector, paired = T)`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(ice_cream_cleaned$vanilla, ice_cream_cleaned$cookie_dough, paired = T)$stderr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.919921\n```\n\n\n:::\n:::\n\n\n\n## Paired Samples *T*-Test Assumptions\n\n::: {style=\"font-size:80%\"}\n:::: {.columns}\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-46-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nice_cream_cleaned |>\n  ggplot(aes(x = difference)) +\n  geom_histogram(aes(y = after_stat(density)), binwidth = 3, alpha = 0.4, color = NA) +\n  geom_density(alpha = 0.6) +\n  theme_classic()\n```\n:::\n\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n::: {.panel-tabset}\n### Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lab_05_files/figure-revealjs/unnamed-chunk-48-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nice_cream_cleaned |>\n  ggplot(aes(sample = difference)) +\n  geom_qq() +\n  geom_qq_line() +\n  theme_classic()\n```\n:::\n\n:::\n\n:::\n::::\n\n:::\n\nNot many data points, but seems OK!\n\n<!-- ```{r} -->\n<!-- ice_cream_sales |> -->\n<!--   ggplot(aes(x = day, y = sales, color = flavor)) + -->\n<!--   geom_point() + -->\n<!--   geom_line() -->\n\n<!-- ice_cream_sales |> -->\n<!--   mutate(.by = flavor, -->\n<!--          moving_average = (lag(sales) + sales + lead(sales)) / 3) |> -->\n<!--   ggplot(aes(x = day, y = moving_average, group = flavor)) + -->\n<!--   geom_step() -->\n\n<!-- ice_cream_cleaned |> -->\n<!--   ggplot(aes(x = day, y = difference)) + -->\n<!--   geom_line() -->\n<!-- ``` -->\n\n\n## *T*-Test: Interpretation and write-up\n\nAn [independent samples / paired samples] *t*-test analysis was conducted between [group 1] and [group 2]. We [[fail to reject]{.navy-color} / [reject]{.gold-color}] $H_0$ [[in favor of $H_1$]{.gold-color}], *t*([df]) = [____], *p* [[< 0.05]{.gold-color} / [p-value]{.navy-color}]. We [[did not]{.navy-color}] observe[[d]{.gold-color}] a significant difference between the mean [outcome] of [group 1] and [group 2] in our sample.\n\n\n<!-- ## Cohen's *D* Revisited -->\n\n<!-- Now that we have two groups, R functions for Cohen's *D* will be more helpful to us. The `cohens_d()` function from the `effectsize` package allows for many formats of inputs. -->\n\n<!-- :::: {.columns} -->\n<!-- ::: {.column width=\"50%\"} -->\n<!-- ```{r} -->\n<!-- #| code-line-numbers: false -->\n<!-- (x_bar_vanilla - x_bar_cookie_dough) / pooled_sd -->\n\n<!-- effectsize::cohens_d(sales ~ candy, -->\n<!--                      data = candy) -->\n<!-- ``` -->\n<!-- ::: -->\n\n<!-- ::: {.column width=\"50%\"} -->\n<!-- ```{r} -->\n<!-- #| code-line-numbers: false -->\n<!-- mean_diff / sd_diff -->\n\n<!-- effectsize::cohens_d(pumpkin$oct1, pumpkin$oct31, -->\n<!--                      paired = T) -->\n<!-- ``` -->\n<!-- ::: -->\n<!-- :::: -->\n\n\n\n\n\n<!-- ::: fragment -->\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- pumpkin <- read.csv(here::here(\"lab\", \"data\", \"lab_04\", \"pumpkin_data.csv\")) -->\n<!-- ``` -->\n\n<!-- ```{r} -->\n<!-- pumpkin <- pumpkin |> -->\n<!--   mutate(diff = oct1 - oct31) -->\n\n<!-- mean_diff <- mean(pumpkin$diff) -->\n<!-- sd_diff <- sd(pumpkin$diff) -->\n<!-- df <- nrow(pumpkin) - 1 -->\n\n<!-- qt(c(.025, .975), df) -->\n\n<!-- t_stat <- (mean_diff - 0) / (sd_diff / sqrt(nrow(pumpkin))) -->\n<!-- t_stat -->\n<!-- ``` -->\n<!-- ::: -->\n\n<!-- [We can reject the null in favor of the alternative that there is a difference in pumpkin weights between October 1st and October 31st in the population!]{.fragment} -->\n\n<!-- ## Cohen's *D* -->\n\n<!-- Standardized mean difference, interpretable effect size -->\n\n<!-- Derived with two means (represented as $\\mu_1$ and $\\mu_2$) and standard deviation ($s$) -->\n\n<!-- $$d = \\frac{\\mu_1 - \\mu_2}{s}$$ -->\n\n<!-- For a one-sample *t* test, $\\mu_1$ would be our sample mean $\\bar{x}$, $\\mu_2$ would be our population mean $\\mu$, and the standard deviation $\\sigma$ would be our observed standard deviation $s$. -->\n\n<!-- Not a statistical test---just a measure of difference. -->\n<!-- ## Cohen's *D* Example -->\n\n<!-- Let's say a researcher claims the average highway miles per gallon across all cars is 30mpg. We found earlier that the sample had a significant difference between the hypothesized and sample mean. What is the effect size of that difference? -->\n\n<!-- $$d = \\frac{\\bar{x} - \\mu}{s}$$ -->\n\n<!-- ::: fragment -->\n<!-- ```{r} -->\n<!-- x_bar <- mean(mpg$hwy) -->\n<!-- x_sd <- sd(mpg$hwy) -->\n\n<!-- d <- (x_bar - 30) / x_sd -->\n<!-- d -->\n<!-- ``` -->\n<!-- ::: -->\n\n<!-- [How would be characterize this difference? What is the direction?]{.fragment} -->\n\n\n<!-- ## Cohen's *D* Strength Visualization -->\n\n<!-- Based on mean ($\\bar{x}$ = `round(x_bar, 2)` = 16.86) and SD ($\\bar{\\sigma}$ = `round(x_sd, 2)` = 4.26) of cars' highway MPG (`hwy`). -->\n\n<!-- Solved backwards for ($\\mu$) based on different potential levels of *d*. \"What would the hypothesized mean have to have been to get different levels of Cohen's *d*?\" -->\n\n<!-- $$\\bar{x} - d \\times s = \\mu$$ -->\n\n<!-- ```{r} -->\n<!-- dat <- data.frame(x = rnorm(100000, x_bar, x_sd)) -->\n\n<!-- mu_ex1 <- x_bar - .2 * x_sd -->\n<!-- mu_ex2 <- x_bar - .5 * x_sd -->\n<!-- mu_ex3 <- x_bar - .8 * x_sd -->\n<!-- ``` -->\n\n\n<!-- ## Cohen's *D* Strength Visualization -->\n\n<!-- \"What would the hypothesized mean have to have been to get different levels of Cohen's *d*?\" -->\n\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-width: 5 -->\n<!-- #| fig-height: 4 -->\n<!-- #| fig-align: center -->\n<!-- ggplot(dat, aes(x = x)) + -->\n<!--   geom_histogram(fill = 'skyblue3', alpha = .4, bins = 16) + -->\n<!--   geom_vline(aes(xintercept = x_bar), -->\n<!--              color = \"skyblue3\", linewidth = 1, linetype = \"dashed\") + -->\n<!--   coord_cartesian(xlim = c(0, 60), expand = F, clip = \"off\") + -->\n<!--   guides(y = \"none\", x = NULL) + -->\n<!--   labs(y = NULL, x = \"Highway MPG\") + -->\n<!--   theme_classic(base_size = 18) -->\n<!-- ``` -->\n\n\n<!-- ## Cohen's *D* Strength Visualization -->\n\n<!-- \"What would the hypothesized mean have to have been to get different levels of Cohen's *d*?\" -->\n\n\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- #| fig-width: 5 -->\n<!-- #| fig-height: 4 -->\n<!-- #| layout-ncol: 3 -->\n<!-- #| fig-align: center -->\n<!-- ggplot(dat, aes(x = x)) + -->\n<!--   geom_histogram(fill = 'skyblue3', alpha = .4, bins = 16) + -->\n<!--   geom_vline(aes(xintercept = x_bar), -->\n<!--              color = \"skyblue3\", linewidth = 1, linetype = \"dashed\") + -->\n<!--   geomtextpath::geom_textvline(aes(xintercept = mu_ex1, label = \"d = 0.2\"), -->\n<!--                                hjust = .3, size = 10, color = \"steelblue4\", linewidth = 1.5) + -->\n<!--   coord_cartesian(xlim = c(0, 60), expand = F, clip = \"off\") + -->\n<!--   guides(y = \"none\", x = NULL) + -->\n<!--   labs(y = NULL, x = \"Highway MPG\") + -->\n<!--   theme_classic(base_size = 18) -->\n\n<!-- ggplot(dat, aes(x = x)) + -->\n<!--   geom_histogram(fill = 'skyblue3', alpha = .4, bins = 16) + -->\n<!--   geom_vline(aes(xintercept = x_bar), -->\n<!--              color = \"skyblue3\", linewidth = 1, linetype = \"dashed\") + -->\n<!--   geomtextpath::geom_textvline(aes(xintercept = mu_ex2, label = \"d = 0.5\"), -->\n<!--                                hjust = .3, size = 10, color = \"steelblue4\", linewidth = 1.5) + -->\n<!--   coord_cartesian(xlim = c(0, 60), expand = F, clip = \"off\") + -->\n<!--   guides(y = \"none\", x = NULL) + -->\n<!--   labs(y = NULL, x = \"Highway MPG\") + -->\n<!--   theme_classic(base_size = 18) -->\n\n<!-- ggplot(dat, aes(x = x)) + -->\n<!--   geom_histogram(fill = 'skyblue3', alpha = .4, bins = 16) + -->\n<!--   geom_vline(aes(xintercept = x_bar), -->\n<!--              color = \"skyblue3\", linewidth = 1, linetype = \"dashed\") + -->\n<!--   geomtextpath::geom_textvline(aes(xintercept = mu_ex3, label = \"d = 0.8\"), -->\n<!--                                hjust = .3, size = 10, color = \"steelblue4\", linewidth = 1.5) + -->\n<!--   coord_cartesian(xlim = c(0, 60), expand = F, clip = \"off\") + -->\n<!--   guides(y = \"none\", x = NULL) + -->\n<!--   labs(y = NULL, x = \"Highway MPG\") + -->\n<!--   theme_classic(base_size = 18) -->\n\n<!-- ``` -->\n\n\n<!-- ## Cohen's *D* in R: One Sample -->\n\n<!-- For one sample, simplest to just program it ourselves `(x_bar - mu) / x_sd` -->\n\n<!-- Example: effect size of observed iris petal length against a hypothesized population mean of 3. -->\n\n<!-- ```{r} -->\n<!-- (mean(iris$Petal.Length) - 3) / sd(iris$Petal.Length) -->\n<!-- ``` -->\n\n\n<!-- ## Cohen's *D* -->\n\n<!-- The `cohens_d()` function from the `effectsize` package allows for many formats of inputs. -->\n\n<!-- :::: {.columns} -->\n<!-- ::: {.column width=\"50%\"} -->\n<!-- ```{r} -->\n<!-- #| code-line-numbers: false -->\n<!-- # install.packages(\"effectsize\") -->\n\n<!-- (x_bar_vanilla - x_bar_cookie_dough) / pooled_sd -->\n\n<!-- effectsize::cohens_d(sales ~ candy, -->\n<!--                      data = candy) -->\n<!-- ``` -->\n<!-- ::: -->\n\n<!-- ::: {.column width=\"50%\"} -->\n<!-- ```{r} -->\n<!-- #| code-line-numbers: false -->\n<!-- mean_diff / sd_diff -->\n\n<!-- effectsize::cohens_d(pumpkin$oct1, pumpkin$oct31, -->\n<!--                      paired = T) -->\n<!-- ``` -->\n<!-- ::: -->\n<!-- :::: -->\n\n\n\n",
    "supporting": [
      "lab_05_files\\figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}